import { PropertyMap } from "@/components/maps/property-map";
import { getDashboardData, getProperties } from "@/lib/site-finder-data";

export default async function MapPage({ searchParams }: { searchParams: Promise<Record<string,string|undefined>> }) {
  const params = await searchParams;
  const [data, dashboard] = await Promise.all([
    getProperties({ status: params.status, screening: params.screening, grade: params.grade, risk: params.risk, confidence: params.confidence, county: params.county, utility: params.utility, pageSize: 100 }),
    getDashboardData(),
  ]);
  return <><div className="finder-page-head"><div><p className="finder-eyebrow">Spatial screening</p><h1>Property intelligence map</h1><p>Cluster and filter stored property coordinates. Provider-derived layers appear only when licensed source geometry has been stored.</p></div></div>
    <div className="finder-toolbar property-filter-toolbar"><form><select className="finder-select" name="status" defaultValue={params.status || ""}><option value="">Any pipeline status</option>{["new","desktop_screening","owner_outreach","site_control","utility_screening","detailed_diligence","candidate_project"].map(item => <option key={item}>{item}</option>)}</select><select className="finder-select" name="screening" defaultValue={params.screening || ""}><option value="">Any screening state</option>{["not_started","queued","running","partially_complete","complete","failed","cancelled"].map(item => <option key={item}>{item}</option>)}</select><input className="finder-field property-county-filter" name="county" defaultValue={params.county} placeholder="County"/><select className="finder-select" name="risk" defaultValue={params.risk || ""}><option value="">Any risk</option>{["low","moderate","high","critical","unknown"].map(item => <option key={item}>{item}</option>)}</select><select className="finder-select" name="confidence" defaultValue={params.confidence || ""}><option value="">Any confidence</option>{["high","moderate","low"].map(item => <option key={item}>{item}</option>)}</select><button className="finder-button">Apply filters</button></form></div>
    <section className="finder-card finder-map"><div className="map-legend"><span><i/>Property</span><span><i className="is-cluster"/>Cluster</span><small>{data.properties.length} matching records · no capacity or feasibility inference</small></div><PropertyMap properties={data.properties} offtakers={dashboard.offtakers as {id:string;company_name:string;latitude:number|null;longitude:number|null}[]} styleUrl={process.env.NEXT_PUBLIC_MAP_STYLE_URL}/></section></>;
}
