export const procurementFaq = [
  { question: "Why should we contract with a new development company?", answer: "The decision should be based on the project structure, contract protections, counterparties, engineering, financing plan, metering, utility approval, and documented responsibilities, not on branding alone. NSoul’s role is to organize those elements into a project that can withstand commercial diligence." },
  { question: "What happens if NSoul cannot complete the project?", answer: "The customer should not be obligated to purchase project energy before the agreed commercial-operation requirements are satisfied. Final documents may also address development conditions, outside dates, assignment, replacement parties, lender rights, and termination." },
  { question: "What happens if the project produces less energy than expected?", answer: "Billing should be based on approved metering and the commercial formula defined in the final agreement. Production estimates, guarantees, reporting duties, remedies, and performance standards must be addressed in definitive documentation." },
  { question: "Will our utility service continue?", answer: "The utility remains central to the project’s interconnection, metering, grid service, and regulated responsibilities. The exact relationship between project energy and utility service depends on the approved commercial and interconnection structure." },
  { question: "Is the proposed 15% discount guaranteed?", answer: "No. It is currently an indicative comparison based on stated assumptions. Final savings require customer billing data, final engineering, utility review, pricing, production estimates, and executed agreements." },
  { question: "What happens if the project is financed or sold?", answer: "Project financing may involve assignment and lender rights. The final documents should define permitted transfers and require approved successors to continue the customer contract." },
  { question: "Who maintains the equipment?", answer: "The intended structure places operations and maintenance responsibility with the project owner and its contracted providers, subject to the final agreement." },
  { question: "How are Renewable Energy Certificates handled?", answer: "The current proposal contemplates transferring associated Renewable Energy Certificates to the off-taker, but ownership, delivery, retirement, and reporting must be defined in the definitive contract." },
  { question: "What information will procurement receive?", answer: "Depending on stage and confidentiality requirements, diligence may include entity information, site control status, utility correspondence, engineering assumptions, production estimates, pricing, insurance, project contracts, development schedule, and risk disclosures." },
] as const;
