"use client";

import { Plus } from "lucide-react";

import { trackEvent } from "@/lib/analytics";

const questions = [
  ["What is a Power Purchase Agreement?", "A PPA is a long-term agreement under which a customer purchases electricity generated by a project at documented commercial terms. Final pricing, delivery, and obligations are established in the signed agreement."],
  ["Does the customer need to purchase the solar equipment?", "Not in the representative structure shown here. NSoul would develop, finance, own, operate, and maintain the project while the customer purchases generated electricity."],
  ["Is the 15% discount guaranteed?", "No. The displayed discount is an indicative development-stage comparison against a modeled utility baseline. Final economics depend on usage, design, utility review, financing, and executed commercial terms."],
  ["Who owns and maintains the system?", "Under the proposed structure, NSoul would own and operate the system, subject to final project documents, financing, and approvals."],
  ["When could the project begin operating?", "The current target is Q2/Q3 2027, but timing remains subject to utility interconnection, engineering, permitting, financing, procurement, construction, and final approvals."],
  ["What happens if utility interconnection is not approved?", "The project cannot proceed as currently contemplated without a viable interconnection path. The scope, schedule, or project itself may need to change based on utility review."],
  ["Can Renewable Energy Certificates be transferred?", "A transfer may be included in the final commercial structure, but ownership and delivery of certificates must be documented in the executed agreement."],
  ["What types of organizations are the best fit?", "Commercial, industrial, healthcare, institutional, distribution, and similar facilities with meaningful, sustained electricity demand may be a fit after energy-use and credit review."],
] as const;

export function FaqSection() {
  return (
    <section className="section faq-section" aria-labelledby="faq-title">
      <div className="container faq-layout">
        <div>
          <p className="eyebrow">Common questions</p>
          <h2 id="faq-title">The commercial model, clarified.</h2>
          <p>Conservative answers for a development-stage energy opportunity.</p>
        </div>
        <div className="faq-list">
          {questions.map(([question, answer]) => (
            <details
              key={question}
              onToggle={(event) => {
                if (event.currentTarget.open) trackEvent("faq_open", { question });
              }}
            >
              <summary><span>{question}</span><Plus aria-hidden="true" /></summary>
              <p>{answer}</p>
            </details>
          ))}
        </div>
      </div>
    </section>
  );
}
