import Link from "next/link";
import { notFound } from "next/navigation";
import { AlertTriangle, CalendarClock, FileText, MapPin, ShieldCheck } from "lucide-react";

import { AssessmentEditor } from "@/components/properties/assessment-editor";
import { ChecklistPanel, ContactsPanel, NotesPanel, RisksPanel, TasksPanel } from "@/components/properties/property-crm-panels";
import { PropertyActions } from "@/components/properties/property-actions";
import { PropertyEditForm } from "@/components/properties/property-edit-form";
import { DocumentUpload } from "@/components/dashboard/document-upload";
import { PropertyMap } from "@/components/maps/property-map";
import { requireSession } from "@/lib/auth/session";
import { getAssignableProfiles, getProperty } from "@/lib/site-finder-data";
import type { PreliminaryScoreRun } from "@/types/property";

const tabs = ["overview","map","assessment","risks","due-diligence","contacts","tasks","documents","notes","activity"];
type Row = Record<string, unknown>;
const rows = (value: unknown) => Array.isArray(value) ? value as Row[] : [];
const one = (value: unknown) => Array.isArray(value) ? value[0] as Row | undefined : value as Row | undefined;
const display = (value: unknown) => value == null || value === "" ? "Not yet verified" : typeof value === "boolean" ? value ? "Yes" : "No" : String(value);

export default async function PropertyDetailPage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ tab?: string; edit?: string }> }) {
  const [{ id }, query, profile, assignees] = await Promise.all([params, searchParams, requireSession(), getAssignableProfiles()]);
  const property = await getProperty(id); if (!property) notFound();
  const tab = tabs.includes(query.tab || "") ? query.tab! : "overview";
  const scoreRuns = Array.isArray(property.property_score_runs) ? property.property_score_runs : property.property_score_runs ? [property.property_score_runs] : [];
  const latestScore = [...scoreRuns].sort((a, b) => b.scored_at.localeCompare(a.scored_at))[0] as PreliminaryScoreRun | undefined;
  const components = rows(latestScore?.property_score_components);
  const riskRows = rows(property.property_risk_flags);
  const unresolvedRisks = riskRows.filter((risk) => risk.active);
  const checklist = rows(property.property_checklist_items).sort((a,b) => Number(a.sort_order) - Number(b.sort_order));
  const taskRows = rows(property.tasks).sort((a,b) => String(b.created_at).localeCompare(String(a.created_at)));
  const activity = rows(property.property_activity);
  const dataSources = rows(property.property_data_sources);
  const utility = one(property.property_utility);
  const canOperate = ["owner","admin","developer"].includes(profile.role);
  const canAssess = ["owner","admin","developer","analyst"].includes(profile.role);
  const assignee = assignees.find((person) => person.id === property.assigned_to);
  const propertyName = property.name || property.project_name || property.address_line_1;
  const isArchived = Boolean(property.archived_at);

  return <>
    <div className="finder-page-head"><div><p className="finder-eyebrow">{property.property_code} · {(property.current_status || property.status).replaceAll("_", " ").replaceAll("-", " ")}</p><h1>{propertyName}</h1><p><MapPin size={12}/> {property.address_line_1}, {property.city}, {property.state} {property.postal_code} · {property.county}</p></div><div className="property-head-actions"><Link className="finder-button finder-button--primary" href={`/dashboard/properties/${id}/screening`}>Site screening</Link>{canOperate && <Link className="finder-button" href="?tab=overview&edit=1">Edit</Link>}<PropertyActions id={id} canEdit={canOperate} canConvert={canOperate && property.current_status !== "promoted_to_project" && !isArchived} archived={isArchived} unresolvedRiskCount={unresolvedRisks.length}/></div></div>
    <div className="property-hero-grid"><section className="finder-card property-score-card"><div className="score-ring" style={{ "--score": latestScore?.displayed_score ?? 0 } as React.CSSProperties}><strong>{latestScore?.displayed_score ?? "—"}</strong></div><div><span className="finder-status finder-status--good">{latestScore ? `Grade ${latestScore.grade}` : "Not assessed"}</span><h2>{latestScore ? `${latestScore.overall_risk} risk · ${latestScore.confidence} confidence` : "Versioned assessment required"}</h2><p>{latestScore ? latestScore.recommendation : "Enter a preliminary assessment without implying project approval or utility capacity."}</p></div></section>{[["Assigned",assignee?.full_name || assignee?.email || "Unassigned"],["Acreage",property.total_acres ?? property.acreage_total ? `${property.total_acres ?? property.acreage_total} acres` : "Unknown"],["Utility",property.utility_name || utility?.electric_utility || "Unconfirmed"],["Site control",property.site_control_status || "Not started"]].map(([label,value]) => <section className="finder-card property-mini" key={label}><span>{label}</span><strong>{value}</strong></section>)}</div>
    <nav className="finder-tabs" aria-label="Property sections">{tabs.map((item) => <Link className={tab === item ? "is-active" : ""} href={`?tab=${item}`} key={item}>{item.replaceAll("-", " ")}</Link>)}</nav>

    {tab === "overview" && <>{query.edit === "1" && canOperate ? <PropertyEditForm property={property}/> : <div className="finder-grid finder-two-col"><section className="finder-card"><div className="finder-card-head"><div><p className="finder-eyebrow">Recommendation</p><h2>{latestScore?.recommendation || "Assessment pending"}</h2></div><span className="evidence-badge">{latestScore?.model_version || "No model"}</span></div><p>{property.notes_summary || property.internal_summary || "No development summary has been recorded."}</p><h3>Top positive factors</h3><div className="evidence-list">{components.filter((item) => Number(item.raw_score) >= 70).slice(0,3).map((item) => <span key={String(item.id)}><ShieldCheck size={14}/>{String(item.category).replaceAll("_", " ")} · {display(item.weighted_score)} points</span>)}{!components.some((item) => Number(item.raw_score) >= 70) && <span>No supported positive factors have been scored.</span>}</div><h3>Top unresolved risks</h3><div className="risk-stack">{unresolvedRisks.slice(0,3).map((risk) => <div className="risk-flag" key={String(risk.id)}><AlertTriangle size={13}/>{String(risk.risk_type).replaceAll("_", " ")}</div>)}{!unresolvedRisks.length && <p>No fatal-risk flag is recorded. This is not a clearance.</p>}</div></section><section className="finder-card"><div className="finder-card-head"><h2>Property facts</h2><span className="evidence-badge">{property.last_verified_at ? "Partially verified" : "Incomplete"}</span></div><div className="fact-grid">{[["Owner",property.owner_name],["Owner mailing",property.owner_mailing_address],["Parcel",property.parcel_number],["Total acreage",property.total_acres ?? property.acreage_total],["Usable acreage",property.estimated_usable_acres ?? property.acreage_usable_estimate],["Asking price",property.asking_price ? `$${property.asking_price.toLocaleString()}` : null],["Price per acre",property.price_per_acre ? `$${property.price_per_acre.toLocaleString()}` : null],["Utility territory",property.utility_territory_status],["Legal access",property.legal_access_status],["Coordinates",property.latitude != null && property.longitude != null ? `${property.latitude}, ${property.longitude}` : null]].map(([label,value]) => <div key={label}><span>{label}</span><strong>{display(value)}</strong></div>)}</div><h3>Source & verification</h3><p>{dataSources.length} provenance record{dataSources.length === 1 ? "" : "s"}; last property verification {property.last_verified_at ? new Date(property.last_verified_at).toLocaleDateString() : "not recorded"}. Estimates and public-source data remain distinct from professional verification.</p></section></div>}</>}
    {tab === "map" && (property.latitude == null || property.longitude == null ? <section className="finder-card finder-empty"><MapPin size={24}/><strong>Coordinates have not been entered</strong><p>Add manual latitude and longitude from the Edit action. No parcel, feeder, substation, flood, wetlands, or utility-capacity layer is inferred.</p></section> : <section className="finder-card finder-map property-detail-map"><PropertyMap properties={[property]} offtakers={[]} styleUrl={process.env.NEXT_PUBLIC_MAP_STYLE_URL}/></section>)}
    {tab === "assessment" && <>{latestScore && <section className="finder-card assessment-summary"><div className="finder-card-head"><div><p className="finder-eyebrow">Latest result</p><h2>{latestScore.displayed_score} / 100 · Grade {latestScore.grade}</h2></div><span className={`risk-tone risk-tone--${latestScore.overall_risk}`}>{latestScore.overall_risk} risk</span></div><div className="assessment-kpis"><span><strong>{latestScore.confidence}</strong>Confidence</span><span><strong>{latestScore.verified_field_count}</strong>Verified</span><span><strong>{latestScore.estimated_field_count || 0}</strong>Estimated</span><span><strong>{latestScore.missing_critical_field_count}</strong>Critical gaps</span><span><strong>{latestScore.model_version}</strong>Model</span></div><div className="score-breakdown">{components.map((item) => <div className="score-row" key={String(item.id)}><span>{String(item.category).replaceAll("_", " ")}<small>{display(item.source_quality)} · {display(item.source_name)}</small></span><i style={{ "--fill": `${Number(item.raw_score)}%` } as React.CSSProperties}/><strong>{display(item.weighted_score)}/{display(item.weight)}</strong></div>)}</div></section>}{canAssess ? <AssessmentEditor propertyId={id}/> : <div className="finder-empty"><strong>Read-only assessment access</strong><p>Your role can review saved results but cannot create a score run.</p></div>}</>}
    {tab === "risks" && <RisksPanel propertyId={id} rows={riskRows} canEdit={canOperate}/>}
    {tab === "due-diligence" && <ChecklistPanel propertyId={id} rows={checklist} canEdit={canOperate} assignees={assignees} documents={rows(property.documents)}/>}
    {tab === "contacts" && <ContactsPanel propertyId={id} rows={rows(property.property_contacts)} canEdit={canOperate}/>}
    {tab === "tasks" && <TasksPanel propertyId={id} rows={taskRows} canEdit={canOperate} checklist={checklist} assignees={assignees}/>}
    {tab === "documents" && <>{canOperate && <DocumentUpload propertyId={id}/>}<RelatedList title="Private property documents" icon={<FileText size={15}/>} rows={rows(property.documents)} empty="No documents have been uploaded to private storage." documentLinks/></>}
    {tab === "notes" && <NotesPanel propertyId={id} rows={rows(property.property_notes)} canEdit={canOperate}/>}
    {tab === "activity" && <section className="finder-card"><div className="finder-card-head"><div><p className="finder-eyebrow">Audit history</p><h2>Chronological activity</h2></div><span>{activity.length}</span></div>{activity.length ? <div className="activity-timeline">{activity.map((item) => <div key={String(item.id)}><CalendarClock size={15}/><div><strong>{String(item.action).replaceAll("_", " ")} · {String(item.entity_type).replaceAll("_", " ")}</strong><small>{new Date(String(item.created_at)).toLocaleString()}</small></div></div>)}</div> : <div className="finder-empty"><strong>No material activity yet</strong><p>Property, score, risk, checklist, contact, task, document, archive, and promotion changes are recorded by trusted database workflows.</p></div>}</section>}
  </>;
}

function RelatedList({ title, icon, rows, empty, documentLinks = false }: { title: string; icon: React.ReactNode; rows: Row[]; empty: string; documentLinks?: boolean }) {
  return <section className="finder-card"><div className="finder-card-head"><h2>{title}</h2><span>{rows.length}</span></div>{rows.length ? <div className="finder-list">{rows.map((item, index) => <div className="finder-list-item" key={String(item.id || index)}><span>{icon}</span><div><strong>{String(item.title || item.document_type || "Related record")}</strong><small>{String(item.original_filename || item.created_at || item.status || "Internal record")}</small></div>{documentLinks && <a className="finder-button" href={`/api/documents/${item.id}`} target="_blank" rel="noreferrer">Signed link</a>}</div>)}</div> : <div className="finder-empty"><strong>No records yet</strong><p>{empty}</p></div>}</section>;
}
