import Link from "next/link";
import { notFound } from "next/navigation";
import { AlertTriangle, ArrowUpRight, CalendarClock, ExternalLink, FileText, MapPin, ShieldCheck } from "lucide-react";
import { PropertyActions } from "@/components/properties/property-actions";
import { TaskQuickCreate } from "@/components/properties/task-quick-create";
import { DocumentUpload } from "@/components/dashboard/document-upload";
import { requireSession } from "@/lib/auth/session";
import { calculatePropertyScore } from "@/lib/scoring/calculate";
import { getProperty } from "@/lib/site-finder-data";

const tabs=["overview","land","utility","environmental","regulatory","economics","off-takers","contacts","documents","notes","activity"];
function one<T>(value:T|T[]|null|undefined){return Array.isArray(value)?value[0]??null:value??null}
function display(value:unknown){if(value===null||value===undefined||value==="")return "Not yet verified";if(typeof value==="boolean")return value?"Yes":"No";return String(value)}
export default async function PropertyDetailPage({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<{tab?:string}>}){const{id}=await params;const query=await searchParams;const profile=await requireSession();const property=await getProperty(id);if(!property)notFound();const tab=tabs.includes(query.tab||"")?query.tab!:"overview";const score=calculatePropertyScore(property);const utility=one(property.property_utility);const environmental=one(property.property_environmental);const regulatory=one(property.property_regulatory);const market=one(property.property_market);const sourceEvidence=property.source_url?"Source-reported":"Unverified";return <><div className="finder-page-head"><div><p className="finder-eyebrow">{property.property_code} · {property.status.replaceAll("-"," ")}</p><h1>{property.project_name||property.address_line_1}</h1><p><MapPin size={12}/> {property.address_line_1}, {property.city}, {property.state} {property.postal_code} · {property.county}</p></div><div className="property-head-actions">{property.source_url&&<a className="finder-button" href={property.source_url} target="_blank" rel="noreferrer">Source <ExternalLink size={14}/></a>}<PropertyActions id={id} canConvert={profile.role==="admin"&&property.status!=="converted-to-project"}/></div></div><div className="property-hero-grid"><section className="finder-card property-score-card"><div className="score-ring" style={{"--score":score.effectiveScore} as React.CSSProperties}><strong>{score.effectiveScore}</strong></div><div><span className="finder-status finder-status--good">{score.category}</span><h2>{score.confidenceLabel}</h2><p>{score.dataConfidence}% of scoring inputs have supporting evidence beyond an unknown default.</p></div></section>{[["Asking price",property.asking_price?`$${property.asking_price.toLocaleString()}`:"Not yet verified"],["Total acreage",property.acreage_total?`${property.acreage_total} acres`:"Not yet verified"],["Assigned analyst",property.assigned_to||"Unassigned"],["Next action",property.next_action||"Not assigned"]].map(([label,value])=><section className="finder-card property-mini" key={label}><span>{label}</span><strong>{value}</strong></section>)}</div><div className="finder-tabs" role="tablist">{tabs.map(item=><Link className={tab===item?"is-active":""} href={`?tab=${item}`} key={item}>{item.replaceAll("-"," ")}</Link>)}</div>
  {tab==="overview"&&<div className="finder-grid finder-two-col"><section className="finder-card"><div className="finder-card-head"><h2>Development recommendation</h2><span className="evidence-badge">{sourceEvidence}</span></div><div className="property-overview"><p>{property.internal_summary||"No internal summary has been recorded."}</p>{score.blockingIssues.length?<div className="risk-stack">{score.blockingIssues.map(issue=><div className="risk-flag" key={issue}><AlertTriangle size={13}/>{issue}</div>)}</div>:<div className="evidence-positive"><ShieldCheck size={15}/>No blocking issue is currently recorded. This is not a clearance or approval.</div>}<h3>Suggested next actions</h3><ol>{score.suggestedNextActions.map(action=><li key={action}>{action}</li>)}</ol></div></section><section className="finder-card"><div className="finder-card-head"><h2>Score breakdown</h2><span className="evidence-badge">{score.version}</span></div><div className="score-breakdown">{score.explanations.map(item=><div className="score-row" title={item.explanation} key={item.key}><span>{item.label}</span><i style={{"--fill":`${item.possible?item.awarded/item.possible*100:0}%`} as React.CSSProperties}/><strong>{item.awarded}/{item.possible}</strong></div>)}</div></section></div>}
  {tab==="land"&&<DataPanel title="Land characteristics" items={[["Total acreage",property.acreage_total],["Potentially usable acreage",property.acreage_usable_estimate],["Property type",property.property_type],["Current use",property.current_land_use],["Tillable status",property.tillable_status],["Cleared percentage",property.cleared_percentage],["Wooded percentage",property.wooded_percentage],["Average slope",property.slope_average_percent],["Legal access",property.legal_access_status],["Parcel number",property.parcel_number]]}/>} 
  {tab==="utility"&&<CautionPanel title="Utility review" caution="A nearby line or substation does not establish service territory, voltage, available capacity, cost, or interconnection feasibility." items={[["Electric utility",utility?.electric_utility],["Service territory confirmed",utility?.service_territory_confirmed],["Distance to three-phase",utility?.distance_to_three_phase_miles],["Circuit capacity status",utility?.circuit_capacity_status],["Evidence level",utility?.verification_status],["Distance to substation",utility?.distance_to_substation_miles]]}/>} 
  {tab==="environmental"&&<CautionPanel title="Environmental screening" caution="Desktop screening is not a wetland delineation, flood determination, Phase I assessment, or agency approval." items={[["FEMA flood zone",environmental?.fema_flood_zone],["Floodplain percentage",environmental?.floodplain_percentage],["Wetlands status",environmental?.wetlands_status],["Wetlands percentage",environmental?.wetlands_percentage],["Prime farmland percentage",environmental?.prime_farmland_percentage],["Evidence level",environmental?.verification_status]]}/>} 
  {tab==="regulatory"&&<CautionPanel title="Regulatory screening" caution="Local requirements must be confirmed in writing with the authority having jurisdiction." items={[["Zoning classification",regulatory?.zoning_classification],["Solar use allowed",regulatory?.solar_use_allowed],["Conditional use required",regulatory?.conditional_use_required],["Evidence level",regulatory?.verification_status]]}/>} 
  {tab==="economics"&&<CautionPanel title="Conceptual economics" caution="Capacity, generation, costs, and development risk remain conceptual until supported by engineering and commercial diligence." items={[["Conceptual capacity MW DC",market?.conceptual_capacity_mw_dc],["Conceptual annual generation",market?.estimated_annual_generation_kwh],["Asking price",property.asking_price],["Price per acre",property.price_per_acre],["Development risk",market?.estimated_development_risk]]}/>} 
  {tab==="off-takers"&&<RelatedList title="Off-taker matches" icon={<ArrowUpRight size={15}/>} rows={(property.property_offtaker_matches as Record<string,unknown>[]|undefined)||[]} empty="No off-taker matches have been recorded. Geographic proximity alone does not establish physical or contractual deliverability."/>}
  {tab==="contacts"&&<RelatedList title="Property contacts" icon={<ShieldCheck size={15}/>} rows={(property.property_contacts as Record<string,unknown>[]|undefined)||[]} empty="No linked owner, broker, utility, or professional contacts."/>}
  {tab==="documents"&&<>{profile.role!=="viewer"&&<DocumentUpload propertyId={id}/>}<div style={{height:12}}/><RelatedList title="Evidence documents" icon={<FileText size={15}/>} rows={(property.documents as Record<string,unknown>[]|undefined)||[]} empty="No documents have been uploaded to the private bucket."/></>}
  {tab==="notes"&&<RelatedList title="Research notes" icon={<FileText size={15}/>} rows={(property.property_notes as Record<string,unknown>[]|undefined)||[]} empty="No internal notes have been recorded."/>}
  {tab==="activity"&&<div className="finder-empty"><CalendarClock size={20}/><strong>Activity is retained in the audit log</strong><p>Important inserts, updates, conversions, score calculations, documents, contacts, and milestone changes are logged by database triggers.</p></div>}
  {profile.role!=="viewer"&&<div className="property-task-action"><TaskQuickCreate propertyId={id}/></div>}
  </>}
function DataPanel({title,items}:{title:string;items:[string,unknown][]}){return <section className="finder-card data-panel"><div className="finder-card-head"><h2>{title}</h2><span className="evidence-badge">Mixed evidence</span></div><div>{items.map(([label,value])=><div key={label}><span>{label}</span><strong>{display(value)}</strong></div>)}</div></section>}
function CautionPanel({title,caution,items}:{title:string;caution:string;items:[string,unknown][]}){return <><div className="risk-flag"><AlertTriangle size={13}/>{caution}</div><DataPanel title={title} items={items}/></>}
function RelatedList({title,icon,rows,empty}:{title:string;icon:React.ReactNode;rows:Record<string,unknown>[];empty:string}){return <section className="finder-card"><div className="finder-card-head"><h2>{title}</h2><span>{rows.length}</span></div>{rows.length?<div className="finder-list">{rows.map((item,index)=><div className="finder-list-item" key={String(item.id||index)}><span>{icon}</span><div><strong>{String(item.title||item.note||item.relationship_type||item.document_type||"Related record")}</strong><small>{String(item.created_at||item.status||"Internal record")}</small></div></div>)}</div>:<div className="finder-empty"><strong>No records yet</strong><p>{empty}</p></div>}</section>}
