export type { UserRole } from "@/lib/auth/roles";
export type PropertyStatus = "new" | "screening" | "researching" | "contacted" | "site-control-discussion" | "due-diligence" | "utility-review" | "shortlisted" | "rejected" | "converted-to-project" | "archived";
export type PropertyPipelineStatus = "new" | "desktop_screening" | "owner_outreach" | "site_control" | "utility_screening" | "detailed_diligence" | "candidate_project" | "promoted_to_project" | "rejected" | "archived";
export type PipelineStage = "discovery" | "desktop-screening" | "owner-outreach" | "preliminary-diligence" | "site-control" | "utility-diligence" | "engineering" | "project-development";
export type EvidenceLevel = "unverified" | "source-reported" | "desktop-estimated" | "third-party-verified" | "agency-utility-confirmed";

export interface PropertyUtility { electric_utility: string | null; distance_to_three_phase_miles: number | null; distance_to_distribution_line_miles: number | null; distance_to_substation_miles: number | null; circuit_capacity_status: string | null; verification_status: string | null; service_territory_confirmed: boolean | null; }
export interface PropertyEnvironmental { fema_flood_zone: string | null; floodplain_percentage: number | null; wetlands_status: string | null; wetlands_percentage: number | null; prime_farmland_percentage: number | null; verification_status: string | null; }
export interface PropertyRegulatory { zoning_classification: string | null; solar_use_allowed: boolean | null; conditional_use_required: boolean | null; verification_status: string | null; }
export interface PropertyMarket { estimated_local_offtaker_strength: string | null; estimated_ppa_fit: string | null; conceptual_capacity_mw_dc: number | null; estimated_annual_generation_kwh: number | null; estimated_development_risk: string | null; }

export interface PropertyScore {
  total_score: number; data_confidence?: number; land_cost_score: number; usable_acreage_score: number; clearing_score: number; slope_score: number; flood_score: number; wetlands_score: number; farmland_score: number; road_access_score: number; utility_proximity_score: number; interconnection_confidence_score: number; zoning_score: number; offtaker_score: number; seller_flexibility_score: number; environmental_risk_score: number; strategic_fit_score: number; score_version: string; calculated_at: string; override_score: number | null; override_reason: string | null;
}

export interface PreliminaryScoreRun { id: string; numeric_score: number; displayed_score: number; grade: "A"|"B"|"C"|"D"|"F"; recommendation: string; overall_risk: "low"|"moderate"|"high"|"critical"|"unknown"; confidence: "high"|"moderate"|"low"; verified_field_count: number; estimated_field_count: number; missing_critical_field_count: number; model_version: string; scored_at: string; override_score: number|null; override_reason: string|null; weighted_outputs?: unknown; property_score_components?: Record<string, unknown>[]; }

export interface PropertyRecord {
  id: string; property_code: string; name?: string; project_name: string | null; status: PropertyStatus; current_status?: PropertyPipelineStatus; pipeline_stage: PipelineStage; source_type: string | null; source?: string|null; source_name: string | null; source_url: string | null; listing_url?: string|null; source_listing_id: string | null; source_collected_at: string | null; source_recorded_at?: string|null; last_verified_at?: string|null; listing_status: string | null; address_line_1: string; address_line_2: string | null; city: string; county: string; state: string; postal_code: string; latitude: number | null; longitude: number | null; parcel_number: string | null; acreage_total: number | null; total_acres?: number|null; acreage_usable_estimate: number | null; estimated_usable_acres?: number|null; asking_price: number | null; price_per_acre: number | null; property_type: string | null; current_land_use: string | null; tillable_status: string | null; cleared_percentage: number | null; wooded_percentage: number | null; slope_average_percent: number | null; legal_access_status: string | null; seller_financing_available: boolean | null; lease_option_possible: boolean | null; purchase_possible: boolean | null; owner_name: string | null; owner_mailing_address?: string|null; broker_name: string | null; internal_summary: string | null; notes_summary?: string|null; utility_name?: string|null; utility_territory_status?: string; site_control_status?: string; next_action: string | null; next_action_due_date: string | null; assigned_to: string | null; created_at: string; updated_at: string; archived_at: string | null; property_scores?: PropertyScore | PropertyScore[] | null; property_score_runs?: PreliminaryScoreRun | PreliminaryScoreRun[] | null; property_utility?: PropertyUtility | PropertyUtility[] | null; property_environmental?: PropertyEnvironmental | PropertyEnvironmental[] | null; property_regulatory?: PropertyRegulatory | PropertyRegulatory[] | null; property_market?: PropertyMarket | PropertyMarket[] | null;
}

export interface ScoreExplanation { key: string; label: string; awarded: number; possible: number; explanation: string; evidence: EvidenceLevel; }
export interface ScoreResult { computedScore: number; effectiveScore: number; category: string; dataConfidence: number; confidenceLabel: string; blockingIssues: string[]; missingCriticalFields: string[]; suggestedNextActions: string[]; explanations: ScoreExplanation[]; version: string; }
