import Link from "next/link";
import { LockKeyhole, Settings2, ShieldCheck, Users } from "lucide-react";
import { requireSession } from "@/lib/auth/session";
import { ADMIN_ROLES } from "@/lib/auth/roles";
import { initialTargetProfile, scoreCategories, scoringWeights } from "@/lib/scoring/config";
import { providerRegistry } from "@/lib/integrations/registry";
import { publicProviderCatalog } from "@/lib/enrichment/registry";

export default async function SettingsPage() {
  const profile = await requireSession();
  const administrator = ADMIN_ROLES.includes(profile.role);
  return <>
    <div className="finder-page-head"><div><p className="finder-eyebrow">Workspace controls</p><h1>Settings and governance</h1><p>Organization identity, scoring configuration, target criteria, providers, document policy, and protected administrative controls.</p></div><span className="evidence-badge">{profile.role} access</span></div>
    <div className="finder-grid finder-two-col">
      <section className="finder-card finder-form-section"><h2>User profile</h2><p>Identity is managed by Supabase Auth. Profile edits are constrained by column grants and row-level security.</p><div className="data-panel"><div><div><span>Name</span><strong>{profile.fullName}</strong></div><div><span>Email</span><strong>{profile.email}</strong></div><div><span>Role</span><strong>{profile.role}</strong></div></div></div></section>
      <section className="finder-card finder-form-section"><h2>Organization access</h2><p>{administrator ? "Invite users, review access state, and administer roles from the secured user directory." : "Only owners and administrators can manage organization access."}</p>{administrator ? <Link className="finder-button finder-button--primary" href="/dashboard/users"><Users size={15} />Manage users</Link> : <button disabled className="finder-button"><LockKeyhole size={15} />Administrator access required</button>}</section>
    </div>
    <section className="finder-card finder-form-section"><h2>Scoring configuration</h2><p>Versioned 100-point model. Changes should create a new version rather than rewriting prior calculations.</p><div className="settings-weight-grid">{Object.entries(scoringWeights).map(([key, value]) => <div key={key}><span>{key.replace(/([A-Z])/g, " $1")}</span><strong>{value} pts</strong></div>)}</div><div className="threshold-row">{scoreCategories.map((item) => <span key={item.label}>{item.min}+ · {item.label}</span>)}</div><button disabled={!administrator} className="finder-button"><Settings2 size={15} />Edit weights</button></section>
    <section className="finder-card finder-form-section"><h2>{initialTargetProfile.name}</h2><p>{initialTargetProfile.notes}</p><pre>{JSON.stringify(initialTargetProfile, null, 2)}</pre><button disabled={!administrator} className="finder-button">Edit target profile</button></section>
    <section className="finder-card finder-form-section"><h2>Source and provider settings</h2><p>Official FEMA, USFWS, and USGS public adapters run without credentials. NLR solar resource requires a server-only key. Remaining categories stay explicit manual workflows until configured.</p><div className="provider-list">{[...providerRegistry.map((provider) => ({ key: provider.key, name: provider.name, configured: provider.enabled, capability: provider.description, note: provider.licensingNotes })), ...publicProviderCatalog().map((provider) => ({ key: provider.key, name: provider.name, configured: provider.configured, capability: provider.description, note: provider.setupInstructions }))].map((provider) => <div className="provider-row" key={provider.key}><div><strong>{provider.name}</strong><p>{provider.capability}</p></div><span className={`finder-status ${provider.configured ? "finder-status--good" : ""}`}>{provider.configured ? "Available" : "Not configured"}</span><p>{provider.note}</p></div>)}</div>{administrator && <Link className="finder-button finder-button--primary" href="/dashboard/settings/integrations">Manage screening integrations</Link>}</section>
    <div className="finder-grid finder-two-col"><section className="finder-card finder-form-section"><h2>Document policy</h2><p>Private bucket · 15 MB maximum · tenant-prefixed paths · signed server-side downloads.</p><span className="evidence-positive"><ShieldCheck size={15} />Public bucket access is disabled by migration policy.</span></section><section className="finder-card finder-form-section"><h2>Data export and danger zone</h2><p>Exports and destructive actions are restricted to owners and administrators. Permanent deletion requires explicit confirmation.</p><button disabled={!administrator} className="finder-button">Request data export</button></section></div>
  </>;
}
