import Link from "next/link";
import { AlertTriangle, ArrowRight, CalendarClock, CheckCircle2, ExternalLink, FileText, Gauge, HelpCircle, Landmark, ListChecks, MessageSquare, ReceiptText, ShieldCheck, Users } from "lucide-react";
import type { UserRole } from "@/lib/auth/roles";
import { getReapWorkspace } from "@/lib/funding/data";
import { calculateReadiness, calculateReimbursementSummary } from "@/lib/funding/domain";
import type { ReadinessResult } from "@/lib/funding/types";
import { FundingAction, FundingContactLinker, FundingRecordStatusControl, LogInteractionButton, ReimbursementPaymentAction, RequirementDocumentLinker, RequirementStatusControl } from "@/components/funding/funding-actions";
import { FundingTabs } from "@/components/funding/funding-tabs";
import { titleCaseStatus } from "@/lib/projects/domain";

type Row=Record<string,unknown>;
const canEditRole=(role:UserRole)=>["owner","admin","developer","analyst"].includes(role);
const money=(value:unknown)=>Number(value??0).toLocaleString(undefined,{style:"currency",currency:"USD",maximumFractionDigits:0});
const projectName=()=>"1 Cornerstone Lane Solar Farm";

export async function ReapWorkspace({projectId,view,role}:{projectId:string;view:string;role:UserRole}){
  const data=await getReapWorkspace(projectId);if(!data)return <section className="funding-empty"><Landmark/><h2>USDA REAP is not configured</h2><p>Create a project funding source before using this workspace.</p></section>;
  const canEdit=canEditRole(role);const template=(data.source as unknown as {funding_program_templates?:Row|null}).funding_program_templates;const primaryContact=(data.contacts as Row[]).find(row=>row.is_primary) as Row|undefined;const nextDeadline=[data.source.application_deadline,...data.requirements.map(row=>row.due_date),...data.milestones.map(row=>row.target_date)].filter(Boolean).sort()[0]??null;
  const primaryContactRecord=primaryContact?.contacts as Row|undefined;const primaryContactName=primaryContactRecord?[primaryContactRecord.first_name,primaryContactRecord.last_name].filter(Boolean).join(" ")||String(primaryContactRecord.company??"Assigned"):"Not assigned";
  const categoryGroups=[
    ["Eligibility",["applicant","registration","site"]],["Documents",["legal","narrative"]],["Engineering",["engineering"]],["Utility",["utility"]],["Environmental",["environmental"]],["Financial",["financial","commercial"]],["Application",["submission","post-award","reimbursement"]],
  ] as const;
  return <section className="funding-workspace reap-workspace"><header className="funding-hero"><div><p className="finder-eyebrow">USDA Rural Development</p><h2>USDA REAP</h2><p>{projectName()} · Internal preparation workspace</p></div><div className="funding-hero-status"><span>Funding status</span><FundingRecordStatusControl projectId={projectId} resource="sources" recordId={data.source.id} status={data.source.status} statuses={["researching","planning","pre-application","preparing","ready-to-submit","submitted","under-review","information-requested","approved","conditionally-approved","denied","withdrawn","closed","reimbursement","completed"]} canEdit={canEdit} label="USDA REAP funding status"/></div></header><FundingTabs projectId={projectId}/>
  {view==="overview"?<><div className="reap-next-action"><div><span><Gauge/>Next Best Action</span><h3>{data.nextBestAction.title}</h3><p>{data.nextBestAction.reason}</p></div>{data.nextBestAction.dueDate?<time>Due {data.nextBestAction.dueDate}</time>:null}</div>
  <div className="reap-facts"><Fact label="Current application" value={data.source.submitted_at?"Submitted":"Not yet submitted"}/><Fact label="Primary USDA contact" value={primaryContactName}/><Fact label="Next deadline" value={nextDeadline??"Not scheduled"}/><Fact label="Application number" value={data.source.application_number??"Not assigned"}/></div>
  <FederalRegistrationCard registration={data.federalRegistration} reapSubmitted={Boolean(data.source.submitted_at)} readiness={calculateReadiness(data.requirements.filter(row=>row.category==="registration"))}/>
  <div className="reap-readiness-grid">{categoryGroups.map(([label,categories])=><ReadinessCard key={label} label={label} readiness={calculateReadiness(data.requirements.filter(row=>(categories as readonly string[]).includes(row.category)))}/>)}<ReadinessCard label="Data confidence" readiness={data.dataConfidence}/></div>
  <TaskBuckets projectId={projectId} buckets={data.taskBuckets}/>
  <div className="funding-two-column"><section className="funding-panel"><PanelTitle icon={AlertTriangle} eyebrow="Actual records" title="Application blockers"/><div className="funding-list">{data.readiness.blockers.slice(0,8).map(row=><article key={row.id}><AlertTriangle/><div><strong>{row.title}</strong><small>{titleCaseStatus(row.category)} · {titleCaseStatus(row.status)}</small></div></article>)}{!data.readiness.blockers.length?<Empty text="No blocking requirements are currently open."/>:null}</div></section><section className="funding-panel"><PanelTitle icon={ShieldCheck} eyebrow="Program information" title="Rules remain separate from project status"/><dl className="funding-definition-list"><div><dt>Program version</dt><dd>{String(template?.version??"Not configured")}</dd></div><div><dt>Date verified</dt><dd>{String(template?.date_verified??"Not verified")}</dd></div><div><dt>Last reviewed by</dt><dd>{String(template?.last_reviewed_by??"Not assigned")}</dd></div></dl><p>Program requirements should be re-verified against current USDA Rural Development guidance before submission.</p>{template?.official_contact_url?<a className="funding-external" href={String(template.official_contact_url)} target="_blank" rel="noreferrer">Oklahoma USDA Rural Development Contacts <ExternalLink/></a>:null}</section></div>
  <section className="funding-panel"><PanelTitle icon={CalendarClock} eyebrow="Application timeline" title="Eleven internal phases"/><div className="reap-timeline">{data.milestones.map((row,index)=>{const phaseReadiness=calculateReadiness(data.requirements.filter(requirement=>phaseCategories(row.phase).includes(requirement.category)));return <article key={row.id}><span>{String(index+1).padStart(2,"0")}</span><div><strong>{row.title}</strong><p>{row.description}</p></div><div><b>{phaseReadiness.percentage==null?titleCaseStatus(row.status):`${phaseReadiness.percentage}%`}</b><small>{phaseReadiness.total?`${phaseReadiness.completed} / ${phaseReadiness.total}`:"No linked requirements"}</small></div></article>})}</div></section></>:null}
  {view==="eligibility"?<RequirementView projectId={projectId} requirements={data.requirements} canEdit={canEdit}/>:null}
  {view==="documents"?<DocumentsView projectId={projectId} sourceId={data.source.id} documents={data.documents as Row[]} requirements={data.requirements} canEdit={canEdit}/>:null}
  {view==="timeline"?<TimelineView milestones={data.milestones}/>:null}
  {view==="contacts"?<ContactsView projectId={projectId} sourceId={data.source.id} contacts={data.contacts as Row[]} availableContacts={data.availableContacts as Row[]} communications={data.communications as Row[]} canEdit={canEdit}/>:null}
  {view==="questions"?<QuestionsView projectId={projectId} sourceId={data.source.id} questions={data.questions as unknown as Row[]} canEdit={canEdit}/>:null}
  {view==="costs"?<CostsView projectId={projectId} sourceId={data.source.id} costs={data.costs as Row[]} canEdit={canEdit}/>:null}
  {view==="reimbursement"?<ReimbursementView projectId={projectId} sourceId={data.source.id} rows={data.reimbursements as Row[]} canEdit={canEdit}/>:null}
  {view==="activity"?<ActivityView communications={data.communications as Row[]} activity={data.activity as Row[]} questions={data.questions as unknown as Row[]}/>:null}
  <p className="project-disclaimer">Internal development workspace. This checklist does not provide legal, tax, financial, engineering, or grant advice and does not establish current USDA requirements, eligibility, funding, award, or approval.</p></section>;
}

function Fact({label,value}:{label:string;value:string}){return <article><span>{label}</span><strong>{value}</strong></article>}
function FederalRegistrationCard({registration,reapSubmitted,readiness}:{registration:NonNullable<Awaited<ReturnType<typeof getReapWorkspace>>>["federalRegistration"];reapSubmitted:boolean;readiness:ReadinessResult}){
  if(!registration)return null;
  const renewal=registration.renewal_date?new Intl.DateTimeFormat("en-US",{month:"long",day:"numeric",year:"numeric"}).format(new Date(`${registration.renewal_date}T12:00:00`)):"Not recorded";
  const registrationReadiness=readiness.state==="configured"?`${readiness.percentage}% · ${readiness.completed} / ${readiness.total} complete`:titleCaseStatus(readiness.state);
  return <section className="funding-panel"><PanelTitle icon={ShieldCheck} eyebrow="Federal registration" title="SAM.gov Financial Assistance"/><dl className="funding-definition-list"><div><dt>UEI</dt><dd>{registration.uei_status==="assigned"?"Assigned · Complete":titleCaseStatus(registration.uei_status)}</dd></div><div><dt>SAM.gov</dt><dd>{registration.registration_status==="active"?"Active · Complete":registration.registration_status==="submitted-pending-activation"?"Submitted · Pending activation":titleCaseStatus(registration.registration_status)}</dd></div><div><dt>Registration</dt><dd>{registration.registration_type}</dd></div><div><dt>Renewal</dt><dd>{renewal}</dd></div><div><dt>Federal registration readiness</dt><dd>{registrationReadiness}</dd></div><div><dt>REAP application</dt><dd>{reapSubmitted?"Submitted":"Preparing · Not submitted"}</dd></div></dl><p>The identifier itself is restricted and is not loaded into this funding view.</p>{registration.official_source_url?<a className="funding-external" href={registration.official_source_url} target="_blank" rel="noreferrer">Open official SAM.gov source <ExternalLink/></a>:null}</section>
}
function ReadinessCard({label,readiness}:{label:string;readiness:ReadinessResult}){const display=readiness.state==="configured"?`${readiness.percentage}%`:readiness.state==="not-applicable"?"N/A":"Not configured";return <article><span>{label}</span><strong>{display}</strong><small>{readiness.state==="configured"?`${readiness.completed} / ${readiness.total} complete`:readiness.state.replaceAll("-"," ")}</small>{readiness.state==="configured"?<i style={{"--progress":`${readiness.percentage}%`} as React.CSSProperties}/>:null}</article>}
function TaskBuckets({projectId,buckets}:{projectId:string;buckets:{overdue:number;today:number;nextSevenDays:number;waiting:number}}){const values:[string,number][]=[["Overdue",buckets.overdue],["Due today",buckets.today],["Next 7 days",buckets.nextSevenDays],["Waiting on third party",buckets.waiting]];return <section className="funding-panel funding-task-panel"><header className="funding-panel-actions"><PanelTitle icon={ListChecks} eyebrow="Existing project tasks" title="Funding task queue"/><Link className="finder-button finder-button--quiet" href={`/dashboard/projects/${projectId}/tasks`}>Open tasks <ArrowRight/></Link></header><div className="funding-task-buckets">{values.map(([label,count])=><article key={label}><span>{label}</span><strong>{count}</strong></article>)}</div></section>}
function PanelTitle({icon:Icon,eyebrow,title}:{icon:typeof Gauge;eyebrow:string;title:string}){return <header className="funding-panel-title"><Icon/><div><p className="finder-eyebrow">{eyebrow}</p><h3>{title}</h3></div></header>}
function Empty({text}:{text:string}){return <div className="funding-empty-inline"><CheckCircle2/><span>{text}</span></div>}
function phaseCategories(phase:string){const map:Record<string,string[]>={planning:["applicant","registration"],"pre-application":["submission"],eligibility:["site"],engineering:["engineering","utility","environmental"],financial:["financial","commercial"],application:["narrative","submission"],review:["submission"],award:["post-award"],construction:["post-award"],reimbursement:["reimbursement"],completed:["post-award"]};return map[phase]??[]}

function RequirementView({projectId,requirements,canEdit}:{projectId:string;requirements:Awaited<ReturnType<typeof getReapWorkspace>> extends infer T?T extends {requirements:infer R}?R:never:never;canEdit:boolean}){const groups=Object.groupBy(requirements,row=>row.category);return <div className="funding-requirement-groups">{Object.entries(groups).map(([category,rows])=><section className="funding-panel" key={category}><header className="funding-category-head"><div><p className="finder-eyebrow">{titleCaseStatus(category)}</p><h3>{calculateReadiness(rows??[]).completed} / {calculateReadiness(rows??[]).total} complete</h3></div></header><div className="funding-requirement-list">{rows?.map(row=><article key={row.id}><div><strong>{row.title}</strong><p>{row.description}</p><small>{row.required?"Required":"Optional"} · {row.blocking?"Blocking":"Non-blocking"} · {titleCaseStatus(row.confirmation_state)}</small></div><RequirementStatusControl projectId={projectId} requirementId={row.id} status={row.status} canEdit={canEdit}/></article>)}</div></section>)}</div>}
function DocumentsView({projectId,documents,requirements,canEdit}:{projectId:string;sourceId:string;documents:Row[];requirements:Awaited<ReturnType<typeof getReapWorkspace>> extends infer T?T extends {requirements:infer R}?R:never:never;canEdit:boolean}){const missing=requirements.filter(row=>row.required&&!row.linked_document_id&&row.status!=="not-applicable");return <div className="funding-two-column"><section className="funding-panel"><PanelTitle icon={FileText} eyebrow="Existing project library" title="REAP document workspace"/><p>Use the existing private document library. Do not upload duplicate evidence.</p><Link className="finder-button finder-button--primary" href={`/dashboard/projects/${projectId}/documents`}>Open project documents <ArrowRight/></Link>{canEdit?<RequirementDocumentLinker projectId={projectId} requirements={missing} documents={documents.map(row=>({id:String(row.id),title:row.title?String(row.title):null,file_name:row.file_name?String(row.file_name):null}))}/>:null}<div className="funding-list">{documents.slice(0,20).map(row=><article key={String(row.id)}><FileText/><div><strong>{String(row.title??row.file_name??"Project document")}</strong><small>{titleCaseStatus(String(row.document_category??row.document_type??"document"))}</small></div></article>)}{!documents.length?<Empty text="No project documents are available."/>:null}</div></section><section className="funding-panel"><PanelTitle icon={ListChecks} eyebrow="Evidence links" title="Requirements needing documents"/><div className="funding-list">{missing.slice(0,20).map(row=><article key={row.id}><AlertTriangle/><div><strong>{row.title}</strong><small>No primary document linked</small></div></article>)}</div></section></div>}
function TimelineView({milestones}:{milestones:NonNullable<Awaited<ReturnType<typeof getReapWorkspace>>>["milestones"]}){return <section className="funding-panel"><PanelTitle icon={CalendarClock} eyebrow="Internal workflow" title="REAP application timeline"/><div className="reap-timeline">{milestones.map((row,index)=><article key={row.id}><span>{String(index+1).padStart(2,"0")}</span><div><strong>{row.title}</strong><p>{row.description}</p></div><div><b>{titleCaseStatus(row.status)}</b><small>{row.target_date?`Target ${row.target_date}`:"No target date"}</small></div></article>)}</div></section>}
function ContactsView({projectId,sourceId,contacts,availableContacts,communications,canEdit}:{projectId:string;sourceId:string;contacts:Row[];availableContacts:Row[];communications:Row[];canEdit:boolean}){return <div className="funding-two-column"><section className="funding-panel"><PanelTitle icon={Users} eyebrow="Existing contact records" title="Funding relationships"/>{canEdit?<FundingContactLinker projectId={projectId} sourceId={sourceId} contacts={availableContacts.map(row=>({id:String(row.id),first_name:row.first_name?String(row.first_name):null,last_name:row.last_name?String(row.last_name):null,company:row.company?String(row.company):null}))}/>:null}<div className="funding-list">{contacts.map(row=>{const contact=row.contacts as Row;const name=[contact?.first_name,contact?.last_name].filter(Boolean).join(" ")||String(contact?.company??"Contact");return <article key={String(row.id)}><Users/><div><strong>{name}</strong><small>{titleCaseStatus(String(row.relationship_type))}{row.is_primary?" · Primary":""}</small></div></article>})}{!contacts.length?<Empty text="No confirmed USDA or funding contact is assigned."/>:null}</div></section><section className="funding-panel"><header className="funding-panel-actions"><PanelTitle icon={MessageSquare} eyebrow="Communication log" title="Recent interactions"/>{canEdit?<LogInteractionButton projectId={projectId} sourceId={sourceId}/>:null}</header><div className="funding-list">{communications.slice(0,20).map(row=><article key={String(row.id)}><MessageSquare/><div><strong>{String(row.subject)}</strong><small>{titleCaseStatus(String(row.direction))} · {new Date(String(row.communication_date)).toLocaleDateString()}</small><p>{String(row.summary)}</p></div></article>)}{!communications.length?<Empty text="No funding communications logged."/>:null}</div></section></div>}
function QuestionsView({projectId,sourceId,questions,canEdit}:{projectId:string;sourceId:string;questions:Row[];canEdit:boolean}){return <section className="funding-panel"><header className="funding-panel-actions"><PanelTitle icon={HelpCircle} eyebrow="Agency review" title="USDA questions and responses"/>{canEdit?<FundingAction projectId={projectId} sourceId={sourceId} kind="questions" label="Log question"/>:null}</header><div className="funding-table">{questions.map(row=><article key={String(row.id)}><div><strong>{String(row.question)}</strong><small>{String(row.source)} · received {new Date(String(row.received_at)).toLocaleDateString()}</small></div><FundingRecordStatusControl projectId={projectId} resource="questions" recordId={String(row.id)} status={String(row.status)} statuses={["open","drafting","waiting","submitted","accepted","closed"]} canEdit={canEdit} label="Agency question status"/><time>{row.due_date?`Due ${String(row.due_date)}`:"No due date"}</time></article>)}{!questions.length?<Empty text="No agency questions recorded."/>:null}</div></section>}
function CostsView({projectId,sourceId,costs,canEdit}:{projectId:string;sourceId:string;costs:Row[];canEdit:boolean}){const estimated=costs.reduce((sum,row)=>sum+Number(row.estimated_cost??0),0),eligible=costs.reduce((sum,row)=>sum+Number(row.eligible_amount??0),0);return <><div className="reap-facts"><Fact label="Estimated tracked cost" value={money(estimated)}/><Fact label="Eligible amount recorded" value={money(eligible)}/><Fact label="Cost items" value={String(costs.length)}/></div><section className="funding-panel"><header className="funding-panel-actions"><PanelTitle icon={ReceiptText} eyebrow="Eligibility evidence" title="Project cost items"/>{canEdit?<FundingAction projectId={projectId} sourceId={sourceId} kind="costs" label="Add cost item"/>:null}</header><div className="funding-table">{costs.map(row=><article key={String(row.id)}><div><strong>{String(row.description)}</strong><small>{String(row.category)} · {titleCaseStatus(String(row.eligibility_status))}</small></div><b>{money(row.eligible_amount??row.estimated_cost)}</b></article>)}{!costs.length?<Empty text="No funding cost items recorded."/>:null}</div></section></>}
function ReimbursementView({projectId,sourceId,rows,canEdit}:{projectId:string;sourceId:string;rows:Row[];canEdit:boolean}){const summary=calculateReimbursementSummary(rows as Array<{requested_amount:number|null;approved_amount:number|null;paid_amount:number|null;status:string}>);return <><div className="reap-facts"><Fact label="Requested" value={money(summary.requested)}/><Fact label="Approved" value={money(summary.approved)}/><Fact label="Paid" value={money(summary.paid)}/><Fact label="Open requests" value={String(summary.open)}/></div><section className="funding-panel"><header className="funding-panel-actions"><PanelTitle icon={ReceiptText} eyebrow="Post-award workflow" title="Reimbursement requests"/>{canEdit?<FundingAction projectId={projectId} sourceId={sourceId} kind="reimbursements" label="New request"/>:null}</header><div className="funding-table">{rows.map(row=><article key={String(row.id)}><div><strong>Request {String(row.request_number)}</strong><FundingRecordStatusControl projectId={projectId} resource="reimbursements" recordId={String(row.id)} status={String(row.status)} statuses={["preparing","submitted","under-review","information-requested","approved","partially-paid","denied"]} canEdit={canEdit} label="Reimbursement status"/></div><span>{money(row.requested_amount)} requested</span><b>{money(row.paid_amount)} paid</b>{String(row.status)!=="paid"?<ReimbursementPaymentAction projectId={projectId} recordId={String(row.id)} canEdit={canEdit}/>:null}</article>)}{!rows.length?<Empty text="No reimbursement requests. This is expected before an award and eligible project costs."/>:null}</div></section></>}
function ActivityView({communications,activity,questions}:{communications:Row[];activity:Row[];questions:Row[]}){const events=[...communications.map(row=>({id:`c-${row.id}`,date:String(row.communication_date),title:String(row.subject),detail:String(row.summary)})),...questions.map(row=>({id:`q-${row.id}`,date:String(row.received_at),title:"Agency question received",detail:String(row.question)})),...activity.map(row=>{const details=(row.after_data??{}) as Row;return {id:`a-${row.id}`,date:String(row.created_at),title:String(details.title??titleCaseStatus(String(row.action))),detail:String(details.description??titleCaseStatus(String(row.entity_type)))};})].sort((a,b)=>new Date(b.date).getTime()-new Date(a.date).getTime());return <section className="funding-panel"><PanelTitle icon={MessageSquare} eyebrow="Unified history" title="REAP activity"/><div className="funding-activity">{events.map(event=><article key={event.id}><time>{new Date(event.date).toLocaleDateString()}</time><div><strong>{event.title}</strong><p>{event.detail}</p></div></article>)}{!events.length?<Empty text="No funding activity recorded."/>:null}</div></section>}
