import Link from "next/link";
import { ArrowUpRight, Building2, FileSignature, HandCoins, Landmark, LockKeyhole } from "lucide-react";
import { getCapitalWorkspace } from "@/lib/finance/data";

type Row=Record<string,unknown>;
export async function CapitalWorkspace({view}:{view:string}){const data=await getCapitalWorkspace();const tabs=[["Overview","/dashboard/capital"],["Partners","/dashboard/capital/partners"],["Opportunities","/dashboard/capital/opportunities"],["Term sheets","/dashboard/capital/term-sheets"]];
return <section className="finance-workspace"><header className="finance-workspace-head"><div><p className="finder-eyebrow">Restricted capital workspace</p><h1>Funding relationships</h1><p>Organization-level partner, lender, investor, and term-sheet intelligence for authorized owners and administrators.</p></div><LockKeyhole/></header><nav className="finance-tabs">{tabs.map(([label,href])=><Link className={(view==="overview"&&href.endsWith("capital"))||href.endsWith(view)?"is-active":""} href={href} key={label}>{label}</Link>)}</nav>
{view==="overview"?<><div className="finance-kpi-grid"><Metric icon={Landmark} label="Capital partners" value={data.partners.length}/><Metric icon={Building2} label="Lender opportunities" value={data.lenderOpportunities.length}/><Metric icon={HandCoins} label="Investor opportunities" value={data.investorOpportunities.length}/><Metric icon={FileSignature} label="Term sheets" value={data.termSheets.length}/></div><div className="finance-main-grid"><List title="Recent partners" rows={data.partners}/><List title="Recent interactions" rows={data.interactions}/></div></>:null}
{view==="partners"?<List title="Capital partner registry" rows={data.partners}/>:null}{view==="opportunities"?<div className="finance-main-grid"><List title="Lender opportunities" rows={data.lenderOpportunities}/><List title="Investor opportunities" rows={data.investorOpportunities}/></div>:null}{view==="term-sheets"?<List title="Financing term sheets" rows={data.termSheets}/>:null}
<p className="project-disclaimer">Confidential relationship data. Terms are preliminary until approved and executed; no financing outcome is guaranteed.</p></section>}
function Metric({icon:Icon,label,value}:{icon:typeof Landmark;label:string;value:number}){return <article className="finance-kpi"><Icon/><span>{label}</span><strong>{value}</strong></article>}
function List({title,rows}:{title:string;rows:Row[]}){return <section className="finance-surface"><header className="finance-surface-title"><div><p className="finder-eyebrow">Capital intelligence</p><h3>{title}</h3></div></header><div className="finance-list">{rows.map((row,index)=><article key={String(row.id||index)}><div><strong>{String(row.name||row.title||row.summary||"Untitled record")}</strong><small>{String(row.partner_type||row.status||row.interaction_type||"record").replaceAll("_"," ")}</small></div><ArrowUpRight/></article>)}{!rows.length?<div className="finance-empty"><Landmark/><strong>No records yet</strong><small>Add verified relationship data through the secured capital API.</small></div>:null}</div></section>}
