import Link from "next/link";
import { AlertTriangle, ArrowUpRight, Banknote, CheckCircle2, CircleDollarSign, FileCheck2, Gauge, Layers3, ShieldCheck, TrendingUp } from "lucide-react";
import type { UserRole } from "@/lib/auth/roles";
import { getFinanceWorkspace } from "@/lib/finance/data";
import { ModelBuilder } from "@/components/finance/model-builder";
import { SensitivityRunner } from "@/components/finance/sensitivity-runner";
import { ReadinessAssessment } from "@/components/finance/readiness-assessment";
import { ProjectRecordForm } from "@/components/projects/project-record-form";

type Row=Record<string,unknown>;
const money=(value:unknown)=>Number(value||0).toLocaleString(undefined,{style:"currency",currency:"USD",maximumFractionDigits:0});
const percent=(value:unknown)=>value==null?"Not available":`${Number(value).toFixed(1)}%`;

export async function FinanceWorkspace({projectId,view,role}:{projectId:string;view:string;role:UserRole}){
  const data=await getFinanceWorkspace(projectId);const latest=data.versions[0] as Row|undefined;const output=(latest?.outputs||{}) as Row;const canEdit=["owner","admin","developer","analyst"].includes(role);const canCapital=["owner","admin"].includes(role);
  const tabs=[["Overview","/finance"],["Models","/finance/models"],["Scenarios","/finance/scenarios"],["Capital stack","/finance/capital-stack"],["Readiness","/finance/readiness"],["Partners","/finance/partners"]];
  return <section className="finance-workspace"><header className="finance-workspace-head"><div><p className="finder-eyebrow">Financial modeling &amp; funding</p><h2>{view==="overview"?"Project finance command center":view.replaceAll("-"," ")}</h2><p>Version-controlled project economics, capital readiness, and funding evidence. All outputs are preliminary and non-binding.</p></div>{canEdit?<ModelBuilder projectId={projectId}/>:null}</header><nav className="finance-tabs" aria-label="Finance workspace">{tabs.map(([label,path])=><Link className={(view==="overview"&&path==="/finance")||path.endsWith(`/${view}`)?"is-active":""} key={label} href={`/dashboard/projects/${projectId}${path}`}>{label}</Link>)}</nav>
  {view==="overview"?<><div className="finance-kpi-grid"><Kpi icon={CircleDollarSign} label="Project NPV" value={money(output.projectNpv)}/><Kpi icon={TrendingUp} label="Project IRR" value={percent(output.projectIrr)}/><Kpi icon={Gauge} label="Minimum DSCR" value={output.minimumDscr?`${Number(output.minimumDscr).toFixed(2)}x`:"Not available"}/><Kpi icon={ShieldCheck} label="Model status" value={latest?String(latest.is_stale?"Stale":latest.status):"Not modeled"}/></div><div className="finance-main-grid"><section className="finance-surface"><SurfaceTitle eyebrow="Current underwriting" title="Latest model version"/><ModelSummary projectId={projectId} version={latest}/></section><section className="finance-surface"><SurfaceTitle eyebrow="Funding readiness" title="Evidence before claims"/><Readiness rows={data.readiness as Row[]} flags={data.flags as Row[]}/></section></div><p className="project-disclaimer">Preliminary development model only. This workspace does not provide investment, tax, legal, or accounting advice and does not guarantee production, savings, incentive eligibility, interconnection, financing, or project approval.</p></>:null}
  {view==="models"?<section className="finance-surface"><SurfaceTitle eyebrow="Immutable versions" title="Financial model registry"/><div className="finance-list">{data.versions.map((row)=><Link key={String(row.id)} href={`/dashboard/projects/${projectId}/finance/models/${row.id}`}><div><strong>{String(row.name)}</strong><small>{String(row.engine_version)} · {String(row.scenario_type)} · {row.is_stale?"stale":"current"}</small></div><span>{String(row.status)}</span><ArrowUpRight/></Link>)}{!data.versions.length?<Empty text="No financial model has been calculated."/>:null}</div></section>:null}
  {view==="scenarios"?<div className="finance-main-grid"><section className="finance-surface"><SurfaceTitle eyebrow="Scenario planning" title="Version-preserved comparisons"/><div className="finance-scenario-grid">{data.versions.slice(0,6).map((row,index)=>{const scenarioOutput=row.outputs as Row;return <Link href={`/dashboard/projects/${projectId}/finance/models/${row.id}`} key={String(row.id)}><article><span>0{index+1} · {String(row.scenario_type)}</span><strong>{String(row.name)}</strong><p>NPV {money(scenarioOutput.projectNpv)} · IRR {percent(scenarioOutput.projectIrr)} · DSCR {scenarioOutput.minimumDscr?`${Number(scenarioOutput.minimumDscr).toFixed(2)}x`:"Not available"}</p></article></Link>})}{!data.versions.length?<Empty text="Create model versions for each comparison case."/>:null}</div></section><section className="finance-surface"><SurfaceTitle eyebrow="Sensitivity" title="Bounded server runs"/><p className="finance-body-copy">Compare cost, generation, pricing, operating expense, and interest-rate changes across a maximum 11 × 11 matrix. Calculations are persisted with the source model version.</p><SensitivityRunner projectId={projectId} modelVersionId={latest?String(latest.id):undefined}/><strong className="finance-big-number">{data.sensitivityRuns.length}</strong><small>saved runs</small></section></div>:null}
  {view==="capital-stack"?<><div className="finance-kpi-grid"><Kpi icon={Banknote} label="Debt facilities" value={String(data.debtFacilities.length)}/><Kpi icon={Layers3} label="Equity sources" value={String(data.equitySources.length)}/><Kpi icon={CircleDollarSign} label="Stack items" value={String(data.stackItems.length)}/><Kpi icon={FileCheck2} label="Term sheets" value={String(data.termSheets.length)}/></div>{canEdit?<div className="finance-inline-actions"><ProjectRecordForm projectId={projectId} section="capital_stack"/><ProjectRecordForm projectId={projectId} section="capital"/></div>:null}<section className="finance-surface"><SurfaceTitle eyebrow="Capital stack" title="Sources, status, and conditions"/><div className="finance-list">{data.stackItems.map(row=><article key={String(row.id)}><div><strong>{String(row.source||row.capital_type)}</strong><small>{String(row.capital_type).replaceAll("_"," ")} · {String(row.status)}</small></div><b>{money(row.amount)}</b></article>)}{!data.stackItems.length?<Empty text="No capital-stack items recorded."/>:null}</div></section></>:null}
  {view==="readiness"?<><div className="finance-inline-actions"><ReadinessAssessment projectId={projectId}/></div><div className="finance-main-grid"><section className="finance-surface"><SurfaceTitle eyebrow="Latest assessment" title="Funding readiness"/><Readiness rows={data.readiness as Row[]} flags={data.flags as Row[]}/></section><section className="finance-surface"><SurfaceTitle eyebrow="Evidence register" title="Readiness requirements"/><div className="finance-list">{data.requirements.map(row=><article key={String(row.id)}><div><strong>{String(row.title)}</strong><small>{String(row.category)} · {String(row.status)}</small></div>{row.status==="complete"?<CheckCircle2/>:<AlertTriangle/>}</article>)}{!data.requirements.length?<Empty text="No readiness requirements recorded."/>:null}</div></section></div></>:null}
  {view==="partners"?<section className="finance-surface"><SurfaceTitle eyebrow="Restricted capital CRM" title="Project funding relationships"/><p className="finance-body-copy">Capital partner terms, requirements, contacts, and interactions are restricted to organization owners and administrators.</p>{canCapital?<div className="finance-list">{data.partners.map(row=><article key={String(row.id)}><div><strong>{String(row.name)}</strong><small>{String(row.partner_type).replaceAll("_"," ")} · {String(row.status)}</small></div><ArrowUpRight/></article>)}{!data.partners.length?<Empty text="No capital partners recorded."/>:null}</div>:<div className="finance-restricted"><ShieldCheck/><strong>Restricted workspace</strong><p>Your role can view project economics but not sensitive capital-partner records.</p></div>}</section>:null}</section>;
}

function Kpi({icon:Icon,label,value}:{icon:typeof Gauge;label:string;value:string}){return <article className="finance-kpi"><Icon/><span>{label}</span><strong>{value}</strong></article>}
function SurfaceTitle({eyebrow,title}:{eyebrow:string;title:string}){return <header className="finance-surface-title"><div><p className="finder-eyebrow">{eyebrow}</p><h3>{title}</h3></div></header>}
function Empty({text}:{text:string}){return <div className="finance-empty"><Layers3/><strong>{text}</strong><small>Create or import a verified record when evidence is available.</small></div>}
function ModelSummary({projectId,version}:{projectId:string;version:Row|undefined}){if(!version)return <Empty text="No financial model has been calculated."/>;const output=version.outputs as Row;return <Link className="finance-model-summary" href={`/dashboard/projects/${projectId}/finance/models/${version.id}`}><div><span>Version {String(version.version_number)}</span><h4>{String(version.name)}</h4><p>{String(version.engine_version)} · Source {String(version.source_hash||"").slice(0,10)}</p></div><dl><div><dt>Equity NPV</dt><dd>{money(output.equityNpv)}</dd></div><div><dt>Equity IRR</dt><dd>{percent(output.equityIrr)}</dd></div><div><dt>Break-even PPA</dt><dd>{output.breakEvenPpaRate?`$${Number(output.breakEvenPpaRate).toFixed(4)}`:"Not available"}</dd></div></dl><ArrowUpRight/></Link>}
function Readiness({rows,flags}:{rows:Row[];flags:Row[]}){const row=rows[0];if(!row)return <div className="finance-readiness-empty"><Gauge/><strong>Not yet assessed</strong><p>Readiness requires an approved current model, approved production and budget sources, valid site control, and interconnection evidence.</p></div>;return <div className="finance-readiness"><strong>{String(row.score)}<small>/100</small></strong><div><span>{String(row.readiness_status).replaceAll("_"," ")}</span><p>{flags.length?`${flags.length} unresolved readiness flags.`:"No recorded fatal flags in the latest assessment."}</p></div></div>}
