import { SCORE_VERSION, scoreCategories, scoringWeights } from "@/lib/scoring/config";
import type { EvidenceLevel, PropertyRecord, ScoreExplanation, ScoreResult } from "@/types/property";
function one<T>(value: T | T[] | null | undefined): T | null { return Array.isArray(value) ? value[0] ?? null : value ?? null; }
function row(key: string, label: string, awarded: number, possible: number, text: string, evidence: EvidenceLevel = "unverified"): ScoreExplanation { return { key, label, awarded: Math.max(0, Math.min(possible, awarded)), possible, explanation: text, evidence }; }

export function calculatePropertyScore(property: Partial<PropertyRecord>): ScoreResult {
  const utility = one(property.property_utility); const environmental = one(property.property_environmental); const regulatory = one(property.property_regulatory); const market = one(property.property_market);
  const rows: ScoreExplanation[] = []; const missing: string[] = []; const blocking: string[] = [];
  const ppa = property.price_per_acre ?? (property.asking_price && property.acreage_total ? property.asking_price / property.acreage_total : null);
  rows.push(row("land", "Land affordability", ppa == null ? 2 : ppa <= 5000 ? 12 : ppa <= 7500 ? 7 : ppa <= 10000 ? 3 : 0, scoringWeights.landAffordability, ppa == null ? "Price per acre is unknown; only limited points are awarded." : `$${Math.round(ppa).toLocaleString()}/acre compared with the $5,000 target.`, ppa == null ? "unverified" : "source-reported")); if (ppa == null) missing.push("Asking price or price per acre");
  const usable = property.acreage_usable_estimate; rows.push(row("usable", "Usable acreage", usable == null ? 1 : usable >= 8 ? 8 : usable >= 5 ? 4 : 0, 8, usable == null ? "Usable acreage has not been estimated." : `${usable} acres are currently considered potentially usable.`, usable == null ? "unverified" : "desktop-estimated")); if (usable == null) missing.push("Usable acreage estimate");
  const cleared = property.cleared_percentage; rows.push(row("clearing", "Cleared / pasture condition", cleared == null ? 2 : cleared >= 80 ? 8 : cleared >= 60 ? 6 : cleared >= 35 ? 3 : 0, 8, cleared == null ? "Clearing condition is unknown." : `${cleared}% reported or estimated cleared.`, cleared == null ? "unverified" : "source-reported"));
  const slope = property.slope_average_percent; rows.push(row("slope", "Slope and topography", slope == null ? 2 : slope <= 3 ? 8 : slope <= 5 ? 6 : slope <= 8 ? 2 : 0, 8, slope == null ? "Average slope is unknown." : `${slope}% average slope.`, slope == null ? "unverified" : "desktop-estimated"));
  const flood = environmental?.floodplain_percentage; rows.push(row("flood", "Flood exposure", flood == null ? 2 : flood <= 2 ? 8 : flood <= 10 ? 5 : flood <= 25 ? 2 : 0, 8, flood == null ? "Flood exposure has not been reviewed." : `${flood}% estimated floodplain exposure.`, flood == null ? "unverified" : "desktop-estimated")); if ((flood ?? 0) >= 25) blocking.push("Material floodplain exposure requires professional review.");
  const wetlands = environmental?.wetlands_percentage; rows.push(row("wetlands", "Wetlands / environmental constraints", wetlands == null ? 2 : wetlands <= 2 ? 8 : wetlands <= 10 ? 5 : wetlands <= 20 ? 2 : 0, 8, wetlands == null ? "Wetlands review is incomplete." : `${wetlands}% potential wetlands exposure.`, wetlands == null ? "unverified" : "desktop-estimated")); if ((wetlands ?? 0) >= 20) blocking.push("Potential wetlands constraints require professional delineation.");
  const prime = environmental?.prime_farmland_percentage; rows.push(row("farmland", "Avoidance of prime farmland", prime == null ? 1 : prime <= 10 ? 5 : prime <= 35 ? 3 : prime <= 65 ? 1 : 0, 5, prime == null ? "Farmland classification is unknown." : `${prime}% estimated prime farmland.`, prime == null ? "unverified" : "desktop-estimated"));
  const access = property.legal_access_status; rows.push(row("access", "Legal road access", access == null ? 1 : access === "confirmed" ? 6 : access === "reported" ? 4 : access === "none" ? 0 : 2, 6, access == null ? "Legal access has not been verified." : `Access status: ${access}.`, access === "confirmed" ? "third-party-verified" : "unverified")); if (access === "none") blocking.push("No confirmed legal access.");
  const threePhase = utility?.distance_to_three_phase_miles; rows.push(row("utility", "Three-phase / distribution proximity", threePhase == null ? 1 : threePhase <= .25 ? 12 : threePhase <= 1 ? 9 : threePhase <= 3 ? 5 : 1, 12, threePhase == null ? "Utility proximity is unknown; visible lines do not establish capacity." : `${threePhase} miles to reported or estimated three-phase infrastructure; capacity remains separate.`, utility?.verification_status === "utility-confirmed" ? "agency-utility-confirmed" : threePhase == null ? "unverified" : "desktop-estimated")); if (threePhase == null) missing.push("Three-phase or distribution proximity");
  const capacity = utility?.circuit_capacity_status; rows.push(row("interconnection", "Interconnection confidence", capacity === "utility-confirmed" ? 10 : capacity === "requested" ? 4 : capacity === "constrained" || capacity === "unavailable" ? 0 : 1, 10, capacity ? `Circuit status: ${capacity}. Proximity alone is not treated as capacity evidence.` : "No utility capacity evidence is available.", capacity === "utility-confirmed" ? "agency-utility-confirmed" : "unverified")); if (!capacity || capacity === "unknown") missing.push("Utility capacity response");
  const solarAllowed = regulatory?.solar_use_allowed; rows.push(row("zoning", "Zoning / permitting fit", solarAllowed == null ? 1 : solarAllowed ? 5 : 0, 5, solarAllowed == null ? "Solar-use treatment has not been confirmed." : solarAllowed ? "Solar use is reported as allowed; verify conditions." : "Solar use is not currently reported as allowed.", solarAllowed == null ? "unverified" : "source-reported"));
  const offtaker = market?.estimated_local_offtaker_strength; rows.push(row("offtaker", "Commercial load / off-taker fit", offtaker === "strong" ? 4 : offtaker === "moderate" ? 2 : offtaker === "weak" ? 0 : 1, 4, offtaker ? `Desktop market assessment: ${offtaker}. Geographic proximity does not establish deliverability.` : "Off-taker fit has not been assessed."));
  const flexible = property.seller_financing_available || property.lease_option_possible; rows.push(row("seller", "Seller flexibility", flexible ? 3 : property.purchase_possible ? 1 : 0, 3, flexible ? "Seller financing or an option structure is reported as possible." : "No advantageous site-control structure is recorded.", flexible ? "source-reported" : "unverified"));
  rows.push(row("strategy", "Strategic county fit", property.state === "Oklahoma" && property.county ? 3 : property.state === "Oklahoma" ? 2 : 0, 3, property.state === "Oklahoma" ? `${property.county || "Oklahoma county"} is within the initial state target; county prioritization remains configurable.` : "Outside the initial Oklahoma target."));
  const computedScore = Math.round(rows.reduce((sum, item) => sum + item.awarded, 0)); const supplied = one(property.property_scores); const effectiveScore = supplied?.override_score ?? computedScore; const verified = rows.filter((item) => item.evidence !== "unverified").length; const dataConfidence = Math.round((verified / rows.length) * 100); const category = scoreCategories.find((item) => effectiveScore >= item.min)?.label ?? "Reject or archive";
  const suggested = [...missing.slice(0, 3).map((item) => `Verify ${item.toLowerCase()}.`), ...(capacity !== "utility-confirmed" ? ["Request written utility service-territory and capacity guidance."] : []), ...(environmental?.verification_status !== "professional-review" ? ["Complete environmental desktop screening before site control."] : [])].slice(0, 5);
  return { computedScore, effectiveScore, category, dataConfidence, confidenceLabel: dataConfidence >= 75 ? "High confidence" : dataConfidence >= 45 ? "Moderate confidence" : "Low confidence", blockingIssues: blocking, missingCriticalFields: missing, suggestedNextActions: suggested, explanations: rows, version: SCORE_VERSION };
}
