"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { CheckCircle2, CircleAlert, Loader2, Plus } from "lucide-react";

type Row = Record<string, unknown>;
const text = (value: unknown) => value == null || value === "" ? "—" : String(value);

async function send(propertyId: string, method: "POST" | "PATCH", body: Record<string, unknown>) {
  const response = await fetch(`/api/properties/${propertyId}/crm`, { method, headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) });
  const result = await response.json();
  if (!response.ok) throw new Error(result.error || "The record could not be saved.");
}

export function ChecklistPanel({ propertyId, rows, canEdit, assignees, documents }: { propertyId: string; rows: Row[]; canEdit: boolean; assignees: Row[]; documents: Row[] }) {
  const [saving, setSaving] = useState<string | null>(null); const [message, setMessage] = useState(""); const router = useRouter();
  async function update(row: Row, status: string, form?: FormData) { setSaving(String(row.id)); setMessage(""); try { await send(propertyId, "PATCH", { resource: "checklist", id: row.id, status, assigned_to: form?.get("assigned_to") || row.assigned_to || null, due_date: form?.get("due_date") || row.due_date || null, notes: form?.get("notes") || row.notes || null, source: form?.get("source") || row.source || null, supporting_document_id: form?.get("supporting_document_id") || row.supporting_document_id || null }); router.refresh(); } catch (error) { setMessage(error instanceof Error ? error.message : "Update failed."); } finally { setSaving(null); } }
  const complete = rows.filter((row) => row.status === "complete" || row.status === "not_applicable").length;
  return <section className="finder-card crm-panel"><div className="finder-card-head"><div><p className="finder-eyebrow">Due diligence</p><h2>{complete} of {rows.length} resolved</h2></div><span className="evidence-badge">Manual workflow</span></div><div className="checklist-list">{rows.map((row) => <div className="checklist-row" key={String(row.id)}><span className={`checklist-dot checklist-dot--${row.status}`}>{row.status === "complete" ? <CheckCircle2 size={18}/> : <CircleAlert size={18}/>}</span><div><strong>{text(row.title)}</strong><small>{text(row.notes || row.source || "No evidence note recorded")}</small>{canEdit && <details className="checklist-details"><summary>Assignment & evidence</summary><form action={(form) => update(row, String(row.status), form)}><select className="finder-select" name="assigned_to" defaultValue={String(row.assigned_to || "")}><option value="">Unassigned</option>{assignees.map((person) => <option key={String(person.id)} value={String(person.id)}>{text(person.full_name || person.email)}</option>)}</select><input className="finder-field" name="due_date" type="date" defaultValue={String(row.due_date || "")}/><select className="finder-select" name="supporting_document_id" defaultValue={String(row.supporting_document_id || "")}><option value="">No evidence document</option>{documents.map((document) => <option key={String(document.id)} value={String(document.id)}>{text(document.title || document.original_filename)}</option>)}</select><input className="finder-field" name="source" placeholder="Source or provider" defaultValue={String(row.source || "")}/><textarea className="finder-textarea" name="notes" placeholder="Evidence, constraints, or missing information" defaultValue={String(row.notes || "")}/><button className="finder-button finder-button--primary" disabled={saving === row.id}>Save evidence</button></form></details>}</div>{canEdit ? <select aria-label={`Status for ${text(row.title)}`} className="finder-select" disabled={saving === row.id} value={String(row.status)} onChange={(event) => update(row, event.target.value)}><option value="not_started">Not started</option><option value="in_progress">In progress</option><option value="complete">Complete</option><option value="not_applicable">Not applicable</option><option value="blocked">Blocked</option></select> : <span className="finder-status">{text(row.status).replaceAll("_", " ")}</span>}</div>)}</div>{message && <p className="risk-flag" role="alert">{message}</p>}<p className="crm-footnote">Assignments, due dates, evidence documents, sources, and notes are retained on each checklist record.</p></section>;
}

export function TasksPanel({ propertyId, rows, canEdit, checklist, assignees }: { propertyId: string; rows: Row[]; canEdit: boolean; checklist: Row[]; assignees: Row[] }) {
  const [open, setOpen] = useState(false); const [saving, setSaving] = useState(false); const [message, setMessage] = useState(""); const router = useRouter();
  async function submit(form: FormData) { setSaving(true); setMessage(""); try { await send(propertyId, "POST", { resource: "task", title: form.get("title"), description: form.get("description") || null, priority: form.get("priority"), assigned_to: form.get("assigned_to") || null, due_date: form.get("due_date") || null, blocker: form.get("blocker") === "on", checklist_item_id: form.get("checklist_item_id") || null }); setOpen(false); router.refresh(); } catch (error) { setMessage(error instanceof Error ? error.message : "Task could not be created."); } finally { setSaving(false); } }
  async function updateStatus(id: unknown, status: string) { await send(propertyId, "PATCH", { resource: "task", id, status }); router.refresh(); }
  return <section className="finder-card crm-panel"><div className="finder-card-head"><h2>Property tasks</h2>{canEdit && <button className="finder-button" onClick={() => setOpen(!open)}><Plus size={14}/>Add task</button>}</div>{open && <form action={submit} className="crm-inline-form"><input className="finder-field" name="title" placeholder="Task title" required/><select className="finder-select" name="priority"><option>normal</option><option>high</option><option>critical</option><option>low</option></select><select className="finder-select" name="assigned_to"><option value="">Unassigned</option>{assignees.map((person) => <option key={String(person.id)} value={String(person.id)}>{text(person.full_name || person.email)}</option>)}</select><input className="finder-field" name="due_date" type="date"/><select className="finder-select" name="checklist_item_id"><option value="">No checklist link</option>{checklist.map((item) => <option value={String(item.id)} key={String(item.id)}>{text(item.title)}</option>)}</select><label><input name="blocker" type="checkbox"/> Blocker</label><textarea className="finder-textarea" name="description" placeholder="Description"/><button className="finder-button finder-button--primary" disabled={saving}>{saving ? <Loader2 className="spin" size={14}/> : <Plus size={14}/>}Create</button></form>}<div className="finder-list">{rows.map((row) => <div className="finder-list-item" key={String(row.id)}><span className={`task-priority task-priority--${row.priority}`}/><div><strong>{text(row.title)} {row.blocker ? "· BLOCKER" : ""}</strong><small>{text(row.status).replaceAll("-", " ")} · {row.due_date ? `Due ${text(row.due_date)}` : "No due date"}</small></div>{canEdit && <select className="finder-select" aria-label={`Status for ${text(row.title)}`} value={String(row.status)} onChange={(event) => updateStatus(row.id, event.target.value)}><option value="open">Open</option><option value="in-progress">In progress</option><option value="waiting">Waiting</option><option value="completed">Completed</option><option value="canceled">Canceled</option></select>}</div>)}</div>{!rows.length && <div className="finder-empty"><strong>No tasks yet</strong><p>Add a task and optionally link it to a diligence item.</p></div>}{message && <p className="risk-flag">{message}</p>}</section>;
}

export function NotesPanel({ propertyId, rows, canEdit }: { propertyId: string; rows: Row[]; canEdit: boolean }) {
  const [saving, setSaving] = useState(false); const [message, setMessage] = useState(""); const router = useRouter();
  async function submit(form: FormData) { setSaving(true); try { await send(propertyId, "POST", { resource: "note", note: form.get("note"), note_type: form.get("note_type") }); router.refresh(); } catch (error) { setMessage(error instanceof Error ? error.message : "Note could not be added."); } finally { setSaving(false); } }
  return <section className="finder-card crm-panel"><div className="finder-card-head"><h2>Property notes</h2><span>{rows.length}</span></div>{canEdit && <form action={submit} className="crm-inline-form"><select name="note_type" className="finder-select"><option>general</option><option>seller-call</option><option>broker-call</option><option>utility</option><option>engineering</option><option>environmental</option><option>legal</option></select><textarea className="finder-textarea" name="note" required placeholder="Add an internal, source-aware note…"/><button className="finder-button finder-button--primary" disabled={saving}>Add note</button></form>}<div className="finder-list">{rows.map((row) => <div className="finder-list-item" key={String(row.id)}><div><strong>{text(row.note_type).replaceAll("-", " ")}</strong><p>{text(row.note)}</p><small>{new Date(String(row.created_at)).toLocaleString()}</small></div></div>)}</div>{message && <p className="risk-flag">{message}</p>}</section>;
}

export function ContactsPanel({ propertyId, rows, canEdit }: { propertyId: string; rows: Row[]; canEdit: boolean }) {
  const [open, setOpen] = useState(false); const [saving, setSaving] = useState(false); const [message, setMessage] = useState(""); const router = useRouter();
  async function submit(form: FormData) { setSaving(true); try { await send(propertyId, "POST", { resource: "contact", relationship_type: form.get("relationship_type"), first_name: form.get("first_name") || null, last_name: form.get("last_name") || null, company: form.get("company") || null, email: form.get("email") || null, phone: form.get("phone") || null, is_primary: form.get("is_primary") === "on" }); setOpen(false); router.refresh(); } catch (error) { setMessage(error instanceof Error ? error.message : "Contact could not be linked."); } finally { setSaving(false); } }
  return <section className="finder-card crm-panel"><div className="finder-card-head"><h2>Linked contacts</h2>{canEdit && <button className="finder-button" onClick={() => setOpen(!open)}><Plus size={14}/>Create & link</button>}</div>{open && <form action={submit} className="crm-inline-form"><select name="relationship_type" className="finder-select">{["owner","broker","attorney","surveyor","engineer","EPC","utility_contact","county_contact","environmental_consultant","lender","investor","offtaker","other"].map((role) => <option key={role}>{role}</option>)}</select><input className="finder-field" name="first_name" placeholder="First name"/><input className="finder-field" name="last_name" placeholder="Last name"/><input className="finder-field" name="company" placeholder="Company"/><input className="finder-field" name="email" type="email" placeholder="Email"/><input className="finder-field" name="phone" placeholder="Phone"/><label><input name="is_primary" type="checkbox"/> Primary</label><button className="finder-button finder-button--primary" disabled={saving}>Link contact</button></form>}<div className="finder-list">{rows.map((row) => { const contact = (row.contacts || {}) as Row; return <div className="finder-list-item" key={String(row.id)}><div><strong>{[contact.first_name, contact.last_name].filter(Boolean).join(" ") || text(contact.company)}</strong><small>{text(row.relationship_type).replaceAll("_", " ")} · {text(contact.email || contact.phone)}</small></div></div>; })}</div>{!rows.length && <div className="finder-empty"><strong>No linked contacts</strong><p>Add an owner, broker, utility contact, or diligence professional.</p></div>}{message && <p className="risk-flag">{message}</p>}</section>;
}

export function RisksPanel({ propertyId, rows, canEdit }: { propertyId: string; rows: Row[]; canEdit: boolean }) {
  const [saving, setSaving] = useState<string | null>(null); const [message, setMessage] = useState(""); const router = useRouter();
  async function update(id: unknown, resolution_status: string) { setSaving(String(id)); try { await send(propertyId, "PATCH", { resource: "risk", id, resolution_status }); router.refresh(); } catch (error) { setMessage(error instanceof Error ? error.message : "Risk could not be updated."); } finally { setSaving(null); } }
  return <section className="finder-card crm-panel"><div className="finder-card-head"><div><p className="finder-eyebrow">Risk register</p><h2>{rows.filter((row) => row.active).length} unresolved flags</h2></div><span className="evidence-badge">Separate from score</span></div><div className="risk-register">{rows.map((row) => <div className="risk-register-row" key={String(row.id)}><CircleAlert size={18}/><div><strong>{text(row.risk_type).replaceAll("_", " ")}</strong><p>{text(row.description || row.explanation)}</p><small>{text(row.severity)} · {text(row.resolution_status || (row.active ? "unresolved" : "resolved"))}</small></div>{canEdit && <select className="finder-select" disabled={saving === row.id} value={String(row.resolution_status || "unresolved")} onChange={(event) => update(row.id, event.target.value)}><option value="unresolved">Unresolved</option><option value="mitigating">Mitigating</option><option value="resolved">Resolved</option><option value="accepted">Accepted</option></select>}</div>)}</div>{!rows.length && <div className="finder-empty"><strong>No risk flags recorded</strong><p>This is not a technical clearance; it means no fatal flag has been entered.</p></div>}{message && <p className="risk-flag">{message}</p>}</section>;
}
