import Link from "next/link";
import { AlertTriangle, ArrowRight, HelpCircle, Landmark, ReceiptText } from "lucide-react";
import { requireSession } from "@/lib/auth/session";
import { getPortfolioFundingWorkspace } from "@/lib/funding/data";
import { titleCaseStatus } from "@/lib/projects/domain";

type Row=Record<string,unknown>;const money=(value:unknown)=>Number(value??0).toLocaleString(undefined,{style:"currency",currency:"USD",maximumFractionDigits:0});
const nestedName=(row:Row)=>{const source=row.project_funding_sources as Row|undefined;const project=(source?.projects??row.projects) as Row|undefined;return String(project?.project_name??"Project")};
export default async function PortfolioFundingPage(){await requireSession();const data=await getPortfolioFundingWorkspace();const reimbursementPending=data.reimbursements.reduce((sum,row)=>["paid","denied"].includes(String(row.status))?sum:sum+Math.max(Number(row.approved_amount??row.requested_amount??0)-Number(row.paid_amount??0),0),0);return <section className="funding-workspace"><header className="funding-hero"><div><p className="finder-eyebrow">Portfolio funding</p><h1>Funding across every project</h1><p>Actual applications, deadlines, blockers, agency questions, and reimbursements from the project funding records.</p></div></header>
<div className="funding-portfolio-kpis"><Kpi label="Projects" value={String(data.projects)}/><Kpi label="Active sources" value={String(data.totals.activeSources)}/><Kpi label="Preparing" value={String(data.totals.preparing)}/><Kpi label="Submitted" value={String(data.totals.submitted)}/><Kpi label="Under review" value={String(data.totals.underReview)}/><Kpi label="Approved" value={String(data.totals.approved)}/><Kpi label="Awarded funding" value={money(data.totals.awardedFunding)}/><Kpi label="Reimbursement pending" value={money(reimbursementPending)}/><Kpi label="Reimbursement received" value={money(data.totals.reimbursementReceived)}/></div>
<section className="funding-panel"><header className="funding-panel-title"><Landmark/><div><p className="finder-eyebrow">Funding by project</p><h2>Source register</h2></div></header><div className="funding-table">{data.sources.map(row=>{const project=row.projects as Row;return <Link key={String(row.id)} href={`/dashboard/projects/${String(row.project_id)}/funding`}><div><strong>{String(row.program_name)}</strong><small>{String(project?.project_name??"Project")} · {titleCaseStatus(String(row.funding_type))}</small></div><span className={`funding-status funding-status--${String(row.status)}`}>{titleCaseStatus(String(row.status))}</span><ArrowRight/></Link>})}</div></section>
<div className="funding-two-column"><section className="funding-panel"><header className="funding-panel-title"><AlertTriangle/><div><p className="finder-eyebrow">Blocking requirements</p><h2>Needs attention</h2></div></header><div className="funding-list">{data.requirements.map(row=><article key={String(row.id)}><AlertTriangle/><div><strong>{String(row.title)}</strong><small>{nestedName(row)} · {titleCaseStatus(String(row.status))}</small></div></article>)}{!data.requirements.length?<p>No blocking requirements recorded.</p>:null}</div></section><section className="funding-panel"><header className="funding-panel-title"><HelpCircle/><div><p className="finder-eyebrow">Open agency questions</p><h2>Response queue</h2></div></header><div className="funding-list">{data.questions.map(row=><article key={String(row.id)}><HelpCircle/><div><strong>{String(row.question)}</strong><small>{nestedName(row)} · {titleCaseStatus(String(row.status))}</small></div></article>)}{!data.questions.length?<p>No open agency questions.</p>:null}</div></section></div>
<div className="funding-two-column"><section className="funding-panel"><header className="funding-panel-title"><AlertTriangle/><div><p className="finder-eyebrow">Upcoming deadlines</p><h2>Funding calendar</h2></div></header><div className="funding-list">{data.deadlines.map(row=><article key={String(row.id)}><AlertTriangle/><div><strong>{String(row.title)}</strong><small>{nestedName(row)} · due {String(row.due_date)}</small></div></article>)}{!data.deadlines.length?<p>No funding deadlines scheduled.</p>:null}</div></section><section className="funding-panel"><header className="funding-panel-title"><Landmark/><div><p className="finder-eyebrow">Recent funding activity</p><h2>Audit stream</h2></div></header><div className="funding-list">{data.activity.map(row=><article key={String(row.id)}><Landmark/><div><strong>{titleCaseStatus(String(row.action))}</strong><small>{titleCaseStatus(String(row.entity_type))} · {new Date(String(row.created_at)).toLocaleDateString()}</small></div></article>)}{!data.activity.length?<p>No recent funding activity.</p>:null}</div></section></div>
<section className="funding-panel"><header className="funding-panel-title"><ReceiptText/><div><p className="finder-eyebrow">Reimbursement pipeline</p><h2>Requests and payments</h2></div></header><div className="funding-table">{data.reimbursements.map(row=><article key={String(row.id)}><div><strong>Request {String(row.request_number)}</strong><small>{nestedName(row)} · {titleCaseStatus(String(row.status))}</small></div><span>{money(row.requested_amount)} requested</span><b>{money(row.paid_amount)} paid</b></article>)}{!data.reimbursements.length?<p>No reimbursement requests recorded.</p>:null}</div></section></section>}
function Kpi({label,value}:{label:string;value:string}){return <article><span>{label}</span><strong>{value}</strong></article>}
