import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowLeft, AlertTriangle, CheckCircle2, Gauge, GitCommitHorizontal } from "lucide-react";
import { ModelApproval } from "@/components/finance/model-approval";
import { getFinancialModelVersion } from "@/lib/finance/data";
import { requireSession } from "@/lib/auth/session";

type Row=Record<string,unknown>;
const value=(entry:unknown,suffix="")=>entry==null?"Not available":`${Number(entry).toLocaleString(undefined,{maximumFractionDigits:2})}${suffix}`;
export default async function ModelDetailPage({params}:PageProps<"/dashboard/projects/[id]/finance/models/[modelId]">){const {id,modelId}=await params;const [profile,model]=await Promise.all([requireSession(),getFinancialModelVersion(id,modelId)]);if(!model)notFound();const outputs=model.outputs as Row;const years=(outputs.years||[]) as Row[];const canApprove=["owner","admin"].includes(profile.role);
return <section className="finance-workspace"><Link className="finance-back" href={`/dashboard/projects/${id}/finance/models`}><ArrowLeft/>All model versions</Link><header className="finance-workspace-head"><div><p className="finder-eyebrow">Immutable model version · {String(model.engine_version)}</p><h2>{String(model.name)}</h2><p>Version {String(model.version_number)} · {String(model.scenario_type)} case · source hash {String(model.source_hash||"not recorded").slice(0,16)}</p></div>{canApprove?<ModelApproval projectId={id} modelId={modelId} disabled={Boolean(model.is_stale)||String(model.status).startsWith("approved")}/>:null}</header>
<div className="finance-kpi-grid"><article className="finance-kpi"><Gauge/><span>Project NPV</span><strong>{value(outputs.projectNpv)}</strong></article><article className="finance-kpi"><GitCommitHorizontal/><span>Project IRR</span><strong>{value(outputs.projectIrr,"%")}</strong></article><article className="finance-kpi"><Gauge/><span>Minimum DSCR</span><strong>{value(outputs.minimumDscr,"x")}</strong></article><article className="finance-kpi">{model.is_stale?<AlertTriangle/>:<CheckCircle2/>}<span>Decision state</span><strong>{model.is_stale?"Stale":String(model.status)}</strong></article></div>
{model.is_stale?<p className="project-disclaimer">This approved version is stale because a material linked source changed. Recalculate and review a new version before relying on the outputs.</p>:null}
<section className="finance-surface"><header className="finance-surface-title"><div><p className="finder-eyebrow">Annual projection</p><h3>Project cash flow and coverage</h3></div></header><div className="finder-table-wrap"><table className="finder-table"><thead><tr><th>Year</th><th>Generation</th><th>Revenue</th><th>O&amp;M</th><th>Debt service</th><th>CFADS</th><th>DSCR</th></tr></thead><tbody>{years.map(year=><tr key={String(year.year)}><td>{String(year.year)}</td><td>{Number(year.generationKwh).toLocaleString()} kWh</td><td>{value(year.revenue)}</td><td>{value(year.opex)}</td><td>{value(year.debtService)}</td><td>{value(year.cfads)}</td><td>{value(year.dscr,"x")}</td></tr>)}</tbody></table></div></section>
<p className="project-disclaimer">Preliminary model; not investment, tax, legal, or accounting advice. Incentive values require current professional verification. Production, savings, interconnection, financing, and approvals are not guaranteed.</p></section>}
