create table if not exists public.public_energy_assessments (
  id uuid primary key default gen_random_uuid(), submitted_at timestamptz not null default now(), first_name text not null, last_name text not null,
  email text not null, company text not null, job_title text not null, phone text, facility_name text not null, facility_address text not null,
  city text not null, state text not null, zip_code text not null, facility_type text not null, current_utility text not null, years_at_facility text,
  annual_electricity_use text, monthly_electricity_spend text, current_blended_rate text, daytime_operating_hours text, electric_meters text,
  demand_charges_known text, peak_demand text, existing_renewable_contracts text, desired_contract_term text, desired_timeline text,
  consent boolean not null check (consent), source_page text, audience text, utm_source text, utm_medium text, utm_campaign text, status text not null default 'new'
);
create table if not exists public.energy_assessment_files (
  id uuid primary key default gen_random_uuid(), assessment_id uuid not null references public.public_energy_assessments(id) on delete cascade,
  storage_path text not null unique, original_filename text not null, mime_type text not null, size_bytes bigint not null check (size_bytes > 0 and size_bytes <= 4194304), created_at timestamptz not null default now()
);
create table if not exists public.public_data_room_requests (
  id uuid primary key default gen_random_uuid(), submitted_at timestamptz not null default now(), name text not null, company text not null,
  title text not null, email text not null, phone text, organization_type text not null, reason text not null, documents_requested text not null,
  nda_willingness text not null, project_relationship text not null, source_page text, utm_source text, utm_medium text, utm_campaign text, status text not null default 'new'
);
alter table public.public_energy_assessments enable row level security;
alter table public.energy_assessment_files enable row level security;
alter table public.public_data_room_requests enable row level security;
revoke all on public.public_energy_assessments, public.energy_assessment_files, public.public_data_room_requests from anon, authenticated;
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('energy-assessment-bills', 'energy-assessment-bills', false, 4194304, array['application/pdf','image/jpeg','image/png','text/csv','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'])
on conflict (id) do update set public = false, file_size_limit = excluded.file_size_limit, allowed_mime_types = excluded.allowed_mime_types;
comment on table public.energy_assessment_files is 'Private storage metadata. Signed URLs may only be generated by authorized server workflows.';
