import Link from "next/link";
import { AlertTriangle, ArrowUpRight, Building2, CalendarClock, CircleDollarSign, FolderKanban, PlugZap, Zap } from "lucide-react";
import { getDashboardData } from "@/lib/site-finder-data";
import { titleCaseStatus } from "@/lib/projects/domain";

type Project=Record<string,unknown>&{project_blockers?:Record<string,unknown>[];project_milestones?:Record<string,unknown>[];project_incentives?:Record<string,unknown>[]};
const money=(value:number)=>`$${value.toLocaleString(undefined,{maximumFractionDigits:0})}`;

export default async function DashboardPage(){
  const data=await getDashboardData();const projects=data.projects as Project[];const active=projects.filter(p=>!["cancelled","decommissioning"].includes(String(p.project_stage))).length;
  const totalDc=projects.reduce((sum,p)=>sum+Number(p.proposed_capacity_mw_dc||0),0);const totalAc=projects.reduce((sum,p)=>sum+Number(p.proposed_capacity_mw_ac||0),0);
  const estimatedCost=projects.reduce((sum,p)=>sum+Number(p.current_budget||0),0);const committed=projects.reduce((sum,p)=>sum+Number(p.committed_capital||0),0);
  const potential=projects.reduce((sum,p)=>sum+Number(p.potential_incentives||0),0);const confirmed=projects.reduce((sum,p)=>sum+Number(p.confirmed_incentives||0),0);
  const critical:Record<string,unknown>[]=projects.flatMap(p=>(p.project_blockers||[]).map(row=>({...row,project_id:p.id,project_name:p.project_name}) as Record<string,unknown>)).filter(row=>row.severity==="critical"&&["open","monitoring"].includes(String(row.status))&&!row.archived_at);
  const overdue:Record<string,unknown>[]=projects.flatMap(p=>(p.project_milestones||[]).map(row=>({...row,project_id:p.id,project_name:p.project_name}) as Record<string,unknown>)).filter(row=>row.target_date&&new Date(String(row.target_date))<new Date()&&!['complete','waived','cancelled'].includes(String(row.status))&&!row.archived_at);
  const priorities=[...critical.map(row=>({kind:"Critical blocker",title:String(row.title),project:String(row.project_name),projectId:String(row.project_id),due:row.target_resolution_date})),...overdue.map(row=>({kind:"Overdue milestone",title:String(row.task_name),project:String(row.project_name),projectId:String(row.project_id),due:row.target_date})),...(data.notifications as Record<string,unknown>[]).map(row=>({kind:titleCaseStatus(String(row.notification_type)),title:String(row.title),project:"Portfolio alert",projectId:String(row.project_id||""),due:row.due_at}))].slice(0,10);
  const metrics=[["Active projects",String(active),FolderKanban],["Pipeline MW DC",totalDc.toFixed(1),Zap],["Pipeline MW AC",totalAc.toFixed(1),PlugZap],["Estimated project cost",money(estimatedCost),CircleDollarSign],["Committed capital",money(committed),CircleDollarSign],["Capital gap",money(Math.max(estimatedCost-committed,0)),AlertTriangle],["Potential incentives",money(potential),CircleDollarSign],["Confirmed incentives",money(confirmed),CircleDollarSign]] as const;
  return <><div className="finder-page-head"><div><p className="finder-eyebrow">Development command center</p><h1>Portfolio operating view</h1><p>Current project readiness, capital exposure, deadlines, and development priorities across the organization.</p></div><Link className="finder-button finder-button--primary" href="/dashboard/projects">Open projects <ArrowUpRight size={15}/></Link></div>
  <div className="project-dashboard-metrics">{metrics.map(([label,value,Icon])=><section key={label}><Icon/><span>{label}</span><strong>{value}</strong></section>)}</div>
  <div className="project-dashboard-grid"><section className="finder-card"><div className="finder-card-head"><div><p className="finder-eyebrow">Current priorities</p><h2>Actions requiring attention</h2></div><span>{priorities.length} open</span></div><div className="project-priority-list">{priorities.map((priority,index)=><Link href={priority.projectId?`/dashboard/projects/${priority.projectId}/overview`:"/dashboard/projects"} key={`${priority.kind}-${index}`}><span className={priority.kind==="Critical blocker"?"is-critical":""}><AlertTriangle/></span><div><strong>{priority.title}</strong><small>{priority.project} · {priority.kind}</small></div><time>{priority.due?new Date(String(priority.due)).toLocaleDateString():"No date"}</time></Link>)}{!priorities.length?<div className="finder-empty"><strong>No critical project priorities</strong><p>New blocker, milestone, utility, commercial, financing, permit, and incentive alerts will appear here.</p></div>:null}</div></section>
  <section className="finder-card"><div className="finder-card-head"><div><p className="finder-eyebrow">Project health</p><h2>Active portfolio</h2></div><Link href="/dashboard/projects">View portfolio</Link></div><div className="project-health-list">{projects.slice(0,8).map(project=><Link key={String(project.id)} href={`/dashboard/projects/${project.id}/overview`}><span className={`project-health project-health--${project.project_health}`}>{titleCaseStatus(String(project.project_health))}</span><div><strong>{String(project.project_name)}</strong><small>{titleCaseStatus(String(project.project_stage))} · {Number(project.proposed_capacity_mw_dc||0)} MW DC</small></div><ArrowUpRight/></Link>)}{!projects.length?<div className="finder-empty"><Building2/><strong>No promoted projects</strong><p>Promote an approved property to begin project development.</p></div>:null}</div></section></div>
  <section className="finder-card project-recent-activity"><div className="finder-card-head"><div><p className="finder-eyebrow">Execution queue</p><h2>Open tasks across projects and properties</h2></div></div><div className="finder-list">{(data.tasks as Record<string,unknown>[]).slice(0,8).map(task=><div className="finder-list-item" key={String(task.id)}><span><CalendarClock size={14}/></span><div><strong>{String(task.title)}</strong><small>{titleCaseStatus(String(task.category||"general"))}</small></div><time>{task.due_date?new Date(String(task.due_date)).toLocaleDateString():"No date"}</time></div>)}{!data.tasks.length?<div className="finder-empty"><strong>No open tasks</strong></div>:null}</div></section></>;
}
