"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { ArrowUpRight, Columns3, List, Search } from "lucide-react";
import { titleCaseStatus } from "@/lib/projects/domain";
import type { ProjectPortfolioRecord } from "@/types/project-command";

function nextMilestone(project: ProjectPortfolioRecord) {
  return (project.project_milestones || []).filter((row) => !row.archived_at && row.status !== "complete" && row.target_date).sort((a,b)=>String(a.target_date).localeCompare(String(b.target_date)))[0];
}
function primaryBlocker(project: ProjectPortfolioRecord) {
  const rank: Record<string, number> = { critical: 4, high: 3, medium: 2, low: 1 };
  return (project.project_blockers || []).filter((row) => !row.archived_at && ["open","monitoring"].includes(String(row.status))).sort((a,b)=>(rank[String(b.severity)]||0)-(rank[String(a.severity)]||0))[0];
}

export function ProjectPortfolio({ projects }: { projects: ProjectPortfolioRecord[] }) {
  const [view, setView] = useState<"table"|"board"|"summary">("table");
  const [search, setSearch] = useState(""); const [stage, setStage] = useState(""); const [health, setHealth] = useState("");
  const [county,setCounty]=useState("");const [utility,setUtility]=useState("");const [interconnection,setInterconnection]=useState("");const [offtaker,setOfftaker]=useState("");const [financing,setFinancing]=useState("");const [blockedOnly,setBlockedOnly]=useState(false);
  const filtered = useMemo(()=>projects.filter((project)=>{
    const query = search.toLowerCase();
    return (!query || `${project.project_name} ${project.location||""} ${project.county||""} ${project.utility||""}`.toLowerCase().includes(query)) && (!stage || project.project_stage===stage) && (!health || project.project_health===health) && (!county||project.county===county) && (!utility||project.utility===utility) && (!interconnection||project.interconnection_status===interconnection) && (!offtaker||project.offtaker_status===offtaker) && (!financing||project.financing_status===financing) && (!blockedOnly||Boolean(primaryBlocker(project)));
  }),[projects,search,stage,health,county,utility,interconnection,offtaker,financing,blockedOnly]);
  const totalDc = filtered.reduce((sum,p)=>sum+Number(p.proposed_capacity_mw_dc||0),0);
  const totalAc = filtered.reduce((sum,p)=>sum+Number(p.proposed_capacity_mw_ac||0),0);
  const capitalGap = filtered.reduce((sum,p)=>sum+Math.max(Number(p.current_budget||0)-Number(p.committed_capital||0),0),0);
  return <div className="project-portfolio">
    <section className="project-portfolio-summary"><div><span>Active projects</span><strong>{filtered.length}</strong></div><div><span>Pipeline MW DC</span><strong>{totalDc.toFixed(1)}</strong></div><div><span>Pipeline MW AC</span><strong>{totalAc.toFixed(1)}</strong></div><div><span>Capital gap</span><strong>${capitalGap.toLocaleString()}</strong></div></section>
    <section className="finder-card project-filterbar"><div className="finder-search"><Search size={16}/><input value={search} onChange={(e)=>setSearch(e.target.value)} placeholder="Search projects, county, utility…"/></div><select className="finder-select" value={stage} onChange={(e)=>setStage(e.target.value)}><option value="">All stages</option>{[...new Set(projects.map(p=>p.project_stage))].map(v=><option key={v} value={v}>{titleCaseStatus(v)}</option>)}</select><select className="finder-select" value={health} onChange={(e)=>setHealth(e.target.value)}><option value="">All health</option>{[...new Set(projects.map(p=>p.project_health))].map(v=><option key={v} value={v}>{titleCaseStatus(v)}</option>)}</select><select className="finder-select" value={county} onChange={e=>setCounty(e.target.value)}><option value="">All counties</option>{[...new Set(projects.map(p=>p.county).filter(Boolean))].map(v=><option key={v!} value={v!}>{v}</option>)}</select><select className="finder-select" value={utility} onChange={e=>setUtility(e.target.value)}><option value="">All utilities</option>{[...new Set(projects.map(p=>p.utility).filter(Boolean))].map(v=><option key={v!} value={v!}>{v}</option>)}</select><select className="finder-select" value={interconnection} onChange={e=>setInterconnection(e.target.value)}><option value="">All interconnection</option>{[...new Set(projects.map(p=>p.interconnection_status).filter(Boolean))].map(v=><option key={v!} value={v!}>{titleCaseStatus(v!)}</option>)}</select><select className="finder-select" value={offtaker} onChange={e=>setOfftaker(e.target.value)}><option value="">All off-taker</option>{[...new Set(projects.map(p=>p.offtaker_status).filter(Boolean))].map(v=><option key={v!} value={v!}>{titleCaseStatus(v!)}</option>)}</select><select className="finder-select" value={financing} onChange={e=>setFinancing(e.target.value)}><option value="">All financing</option>{[...new Set(projects.map(p=>p.financing_status).filter(Boolean))].map(v=><option key={v!} value={v!}>{titleCaseStatus(v!)}</option>)}</select><label className="project-blocked-filter"><input type="checkbox" checked={blockedOnly} onChange={e=>setBlockedOnly(e.target.checked)}/>Active blockers</label><div className="project-view-toggle"><button className={view==="table"?"is-active":""} onClick={()=>setView("table")} aria-label="Table view"><List size={16}/></button><button className={view==="board"?"is-active":""} onClick={()=>setView("board")} aria-label="Stage board"><Columns3 size={16}/></button><button className={view==="summary"?"is-active":""} onClick={()=>setView("summary")} aria-label="Portfolio summary">Σ</button></div></section>
    {view==="table"?<section className="finder-card finder-table-wrap"><table className="finder-table project-table"><thead><tr><th>Project</th><th>Stage / health</th><th>Capacity</th><th>Commercial</th><th>Capital</th><th>Next milestone</th><th>Primary blocker</th><th>Updated</th></tr></thead><tbody>{filtered.map((p)=>{const milestone=nextMilestone(p);const blocker=primaryBlocker(p);return <tr key={p.id}><td data-label="Project"><Link href={`/dashboard/projects/${p.id}/overview`}><strong>{p.project_name}</strong><small>{p.location||p.county||"Location pending"}</small></Link></td><td data-label="Stage"><span className={`project-health project-health--${p.project_health}`}>{titleCaseStatus(p.project_health)}</span><small>{titleCaseStatus(p.project_stage)}</small></td><td data-label="Capacity">{p.proposed_capacity_mw_dc??"Not available"} MW DC<small>{p.proposed_capacity_mw_ac??"Not available"} MW AC</small></td><td data-label="Commercial">{titleCaseStatus(p.offtaker_status)}<small>PPA · {titleCaseStatus(p.financing_status)}</small></td><td data-label="Capital">${Number(p.committed_capital||0).toLocaleString()}<small>${Math.max(Number(p.current_budget||0)-Number(p.committed_capital||0),0).toLocaleString()} gap</small></td><td data-label="Next milestone">{String(milestone?.task_name||"Not scheduled")}<small>{String(milestone?.target_date||"")}</small></td><td data-label="Primary blocker">{String(blocker?.title||"No active blocker")}<small>{titleCaseStatus(String(blocker?.severity||"clear"))}</small></td><td data-label="Updated">{new Date(p.updated_at).toLocaleDateString()} <ArrowUpRight size={14}/></td></tr>})}</tbody></table>{!filtered.length?<div className="finder-empty"><strong>No matching projects</strong><p>Adjust the portfolio filters or promote an approved property.</p></div>:null}</section>:null}
    {view==="board"?<div className="project-stage-board">{[...new Set(filtered.map(p=>p.project_stage))].map(stageName=><section className="finder-card" key={stageName}><header><span>{titleCaseStatus(stageName)}</span><strong>{filtered.filter(p=>p.project_stage===stageName).length}</strong></header>{filtered.filter(p=>p.project_stage===stageName).map(p=><Link href={`/dashboard/projects/${p.id}/overview`} key={p.id}><strong>{p.project_name}</strong><small>{p.proposed_capacity_mw_dc||"Not available"} MW DC · {titleCaseStatus(p.project_health)}</small></Link>)}</section>)}</div>:null}
    {view==="summary"?<div className="project-summary-grid">{["on_track","attention","at_risk","blocked","unknown"].map(tone=><section className="finder-card" key={tone}><span>{titleCaseStatus(tone)}</span><strong>{filtered.filter(p=>p.project_health===tone).length}</strong><small>projects</small></section>)}</div>:null}
  </div>;
}
