import { Activity, AlertCircle, Banknote, CalendarClock, Factory, FileCheck2, FileText, Gauge, Landmark, PlugZap, ShieldCheck, Users, Wrench } from "lucide-react";
import { DocumentUpload } from "@/components/dashboard/document-upload";
import { ProjectRecordForm } from "@/components/projects/project-record-form";
import { calculateCapitalStack, titleCaseStatus } from "@/lib/projects/domain";
import type { ProjectCommandData } from "@/types/project-command";

type Row=Record<string,unknown>;
const date=(value:unknown)=>value?new Date(String(value)).toLocaleDateString():"—";
const money=(value:unknown)=>value==null?"—":`$${Number(value).toLocaleString(undefined,{maximumFractionDigits:0})}`;
const value=(input:unknown)=>input==null||input===""?"—":String(input);

const sectionMeta={
  interconnection:{eyebrow:"Utility pathway",title:"Interconnection",description:"Separate nearby infrastructure and preliminary feedback from formal study results and executed agreements.",icon:PlugZap},
  engineering:{eyebrow:"Technical development",title:"Engineering + EPC",description:"Control design versions, engineering deliverables, equipment assumptions, and comparable EPC proposals without reducing selection to price alone.",icon:Wrench},
  offtakers:{eyebrow:"Commercial pipeline",title:"Off-taker development",description:"Track qualified energy buyers, load evidence, credit review, outreach, and accountable follow-up.",icon:Users},
  ppa:{eyebrow:"Commercial agreement",title:"PPA scenarios",description:"Preserve each pricing and legal version. An unsigned scenario is never represented as a binding PPA.",icon:Landmark},
  permitting:{eyebrow:"Approvals + diligence",title:"Permitting and diligence",description:"Coordinate agencies, submissions, conditions, expiration dates, and property-development findings.",icon:ShieldCheck},
  finance:{eyebrow:"Capital readiness",title:"Budget and capital stack",description:"Compare approved project cost with committed sources. Funding is complete only when committed capital covers current cost.",icon:Banknote},
  incentives:{eyebrow:"Review required",title:"Funding and incentives",description:"Track potential programs, verification sources, missing requirements, deadlines, and confirmed values without implying eligibility.",icon:FileCheck2},
  documents:{eyebrow:"Private document room",title:"Project documents",description:"Tenant-scoped evidence with version, confidentiality, signed status, expiry, and linked-record context.",icon:FileText},
  tasks:{eyebrow:"Execution queue",title:"Milestones and tasks",description:"Coordinate critical-path dates, dependencies, blockers, ownership, and the next required action.",icon:CalendarClock},
  construction:{eyebrow:"Delivery foundation",title:"Construction controls",description:"Record manual progress, cost impacts, change context, and commissioning readiness without implying a live field integration.",icon:Factory},
  operations:{eyebrow:"Asset foundation",title:"Operations readiness",description:"Establish operating asset and maintenance records without representing live SCADA or automated production data.",icon:Gauge},
  activity:{eyebrow:"Immutable operating history",title:"Project activity",description:"Chronological material events across stage, utility, commercial, finance, documents, and execution records.",icon:Activity},
} as const;

export function ProjectModuleView({project,section}:{project:ProjectCommandData;section:string}){
  const meta=sectionMeta[section as keyof typeof sectionMeta];if(!meta)return null;const Icon=meta.icon;
  return <div className="project-module"><header className="project-module-head"><div><p className="finder-eyebrow">{meta.eyebrow}</p><h2>{meta.title}</h2><p>{meta.description}</p></div><div className="project-module-head-actions"><Icon/>{section==="engineering"?<><ProjectRecordForm projectId={project.id} section="engineering"/><ProjectRecordForm projectId={project.id} section="epc"/></>:section==="finance"?<><ProjectRecordForm projectId={project.id} section="budget"/><ProjectRecordForm projectId={project.id} section="capital_stack"/><ProjectRecordForm projectId={project.id} section="capital"/></>:section==="tasks"?<><ProjectRecordForm projectId={project.id} section="milestones"/><ProjectRecordForm projectId={project.id} section="tasks"/></>:<ProjectRecordForm projectId={project.id} section={section}/>}</div></header><ModuleContent project={project} section={section}/></div>
}

function ModuleContent({project,section}:{project:ProjectCommandData;section:string}){
  if(section==="interconnection")return <RecordTable rows={project.interconnection_requests} columns={[["utility_response","Utility response"],["status","Status"],["evidence_level","Evidence"],["application_number","Application"],["requested_capacity_mw","Requested MW"],["deposit","Deposit"],["estimated_upgrade_cost","Est. upgrades"],["next_action","Next action"],["next_action_date","Due"]]} format={{deposit:money,estimated_upgrade_cost:money,next_action_date:date}} empty="No interconnection request is recorded. Nearby electrical infrastructure is not a utility determination."/>;
  if(section==="engineering")return <div className="project-module-stack"><ModuleBand title="Engineering deliverables" count={project.engineering_deliverables.length}><RecordTable rows={project.engineering_deliverables} columns={[["title","Deliverable"],["deliverable_type","Type"],["status","Status"],["target_date","Target"],["delivered_date","Delivered"]]} format={{target_date:date,delivered_date:date}} empty="No engineering deliverables recorded."/></ModuleBand><ModuleBand title="EPC proposal comparison" count={project.epc_proposals.length}><RecordTable rows={project.epc_proposals} columns={[["version_number","Version"],["vendor_id","Vendor"],["total_epc_cost","Total EPC"],["cost_per_watt_dc","$/W DC"],["schedule_summary","Schedule"],["warranty","Warranty"],["proposal_expiration","Expires"],["status","Status"]]} format={{total_epc_cost:money,proposal_expiration:date}} empty="No EPC proposal versions. Document scope, exclusions, schedule, warranty, bonding, and risk before recommending a vendor."/></ModuleBand></div>;
  if(section==="offtakers")return <div className="project-module-stack"><RecordTable rows={project.offtaker_opportunities} columns={[["facility","Facility"],["industry","Industry"],["estimated_annual_usage_kwh","Annual kWh"],["credit_review_status","Credit review"],["interest_level","Interest"],["status","Stage"],["next_action","Next action"]]} empty="No potential energy buyer is linked to this project."/><ModuleBand title="Recent outreach" count={project.offtaker_outreach.length}><RecordTable rows={project.offtaker_outreach} columns={[["outreach_type","Type"],["occurred_at","Date"],["summary","Summary"],["follow_up","Follow-up"],["follow_up_date","Due"]]} format={{occurred_at:date,follow_up_date:date}} empty="No outreach activity recorded."/></ModuleBand></div>;
  if(section==="ppa")return <RecordTable rows={project.ppa_scenarios} columns={[["version_number","Version"],["status","Status"],["term_years","Term"],["starting_price_per_kwh","Starting $/kWh"],["annual_escalator_pct","Escalator"],["contracted_energy_kwh","Contracted kWh"],["legal_review_status","Legal"],["executed_confirmation","Signed confirmation"]]} empty="No PPA scenario exists. New versions remain indicative until executed evidence is attached."/>;
  if(section==="permitting")return <div className="project-module-stack"><ModuleBand title="Permit requirements" count={project.permit_requirements.length}><RecordTable rows={project.permit_requirements} columns={[["requirement_type","Requirement"],["responsible_agency","Agency"],["status","Status"],["application_number","Application"],["due_date","Due"],["approval_date","Approved"],["expiration_date","Expires"],["cost","Cost"]]} format={{due_date:date,approval_date:date,expiration_date:date,cost:money}} empty="No permit requirements have been scoped."/></ModuleBand><ModuleBand title="Diligence register" count={project.diligence_items.length}><RecordTable rows={project.diligence_items} columns={[["title","Item"],["diligence_type","Type"],["status","Status"],["risk_level","Risk"],["due_date","Due"],["findings","Findings"]]} format={{due_date:date}} empty="No diligence items recorded."/></ModuleBand></div>;
  if(section==="finance"){
    const stack=project.capital_stack_versions[0];const items=project.capital_stack_items.filter(row=>row.capital_stack_version_id===stack?.id);const summary=calculateCapitalStack(Number(stack?.approved_project_cost||project.project_budget_versions[0]?.total_project_cost||project.current_budget||0),items.map(row=>({amount:Number(row.amount||0),status:String(row.status),capitalType:String(row.capital_type)})));
    return <div className="project-module-stack"><section className="project-finance-rail"><div><span>Project cost</span><strong>{money(summary.totalProjectCost)}</strong></div><div><span>Committed</span><strong>{money(summary.committedCapital)}</strong></div><div><span>Capital gap</span><strong>{money(summary.capitalGap)}</strong></div><div><span>Readiness</span><strong>{summary.fullyFinanced?"Fully funded":"Funding incomplete"}</strong></div></section><ModuleBand title="Budget versions" count={project.project_budget_versions.length}><RecordTable rows={project.project_budget_versions} columns={[["version_number","Version"],["name","Budget"],["status","Status"],["total_project_cost","Total cost"],["approved_at","Approved"]]} format={{total_project_cost:money,approved_at:date}} empty="No versioned project budget recorded."/></ModuleBand><ModuleBand title="Capital stack" count={items.length}><RecordTable rows={items} columns={[["capital_type","Type"],["source","Source"],["amount","Amount"],["status","Status"],["expected_close_date","Expected close"],["conditions","Conditions"]]} format={{amount:money,expected_close_date:date}} empty="Create a capital-stack version before adding funding sources."/></ModuleBand><p className="project-disclaimer">Financial records are preliminary planning records and are not investment, tax, legal, or accounting advice.</p></div>;
  }
  if(section==="incentives")return <><RecordTable rows={project.project_incentives} columns={[["incentive_program_id","Program"],["eligibility_status","Eligibility"],["application_status","Application"],["estimated_value","Estimated"],["confirmed_value","Confirmed"],["deadline","Deadline"],["last_verified_date","Verified"],["next_action","Next action"]]} format={{estimated_value:money,confirmed_value:money,deadline:date,last_verified_date:date}} empty="No project incentive records. Seeded program definitions require current verification before use."/><p className="project-disclaimer">Potential programs are review-required records and not professional advice. No incentive is represented as confirmed without a verified project record.</p></>;
  if(section==="documents")return <div className="project-module-stack"><DocumentUpload projectId={project.id}/><RecordTable rows={project.documents} columns={[["title","Document"],["document_type","Category"],["version","Version"],["confidentiality","Confidentiality"],["document_status","Status"],["is_signed","Signed"],["expires_at","Expires"],["created_at","Added"]]} format={{expires_at:date,created_at:date}} empty="No project documents uploaded."/></div>;
  if(section==="tasks")return <div className="project-module-stack"><ModuleBand title="Milestones" count={project.project_milestones.length}><RecordTable rows={project.project_milestones} columns={[["task_name","Milestone"],["project_stage","Stage"],["status","Status"],["critical_path","Critical path"],["target_date","Target"],["completed_date","Actual"],["blocker_status","Blocker"]]} format={{target_date:date,completed_date:date}} empty="No project milestones."/></ModuleBand><ModuleBand title="Execution tasks" count={project.tasks.length}><RecordTable rows={project.tasks} columns={[["title","Task"],["category","Category"],["priority","Priority"],["status","Status"],["assigned_to","Owner"],["due_date","Due"]]} format={{due_date:date}} empty="No open project tasks."/></ModuleBand></div>;
  if(section==="construction")return <><RecordTable rows={project.construction_progress_updates} columns={[["title","Update"],["record_type","Workstream"],["status","Status"],["effective_date","Reported"],["due_date","Next due"],["amount","Cost impact"],["details","Details"]]} format={{effective_date:date,due_date:date,amount:money}} empty="No manual construction progress updates are recorded."/><p className="project-disclaimer">Construction records are a manual operating foundation and do not imply field-system integration or verified completion.</p></>;
  if(section==="operations")return <><RecordTable rows={project.operating_assets} columns={[["title","Asset"],["record_type","Type"],["status","Status"],["effective_date","Effective"],["due_date","Next service"],["details","Details"]]} format={{effective_date:date,due_date:date}} empty="No operating asset has been commissioned into the manual register."/><p className="project-disclaimer">Operations records are manual. No live SCADA, meter, or automated production feed is connected.</p></>;
  if(section==="activity")return <div className="project-activity-log">{project.activity.map(row=><article key={String(row.id)}><span><Activity/></span><div><strong>{titleCaseStatus(String(row.action))}</strong><p>{titleCaseStatus(String(row.entity_type))}</p></div><time>{date(row.created_at)}</time></article>)}{!project.activity.length?<div className="finder-empty"><AlertCircle/><strong>No project activity available</strong><p>Material changes will appear here after the Sprint 4 migration is applied.</p></div>:null}</div>;
  return null;
}

function ModuleBand({title,count,children}:{title:string;count:number;children:React.ReactNode}){return <section className="project-module-band"><header><h3>{title}</h3><span>{count} records</span></header>{children}</section>}
function RecordTable({rows,columns,format={},empty}:{rows:Row[];columns:[string,string][];format?:Record<string,(value:unknown)=>string>;empty:string}){return <div className="finder-card finder-table-wrap project-record-table"><table className="finder-table"><thead><tr>{columns.map(([,label])=><th key={label}>{label}</th>)}</tr></thead><tbody>{rows.map((row,index)=><tr key={String(row.id||index)}>{columns.map(([key,label])=><td data-label={label} key={key}>{format[key]?format[key](row[key]):typeof row[key]==="boolean"?(row[key]?"Yes":"No"):titleCaseStatus(value(row[key]))}</td>)}</tr>)}</tbody></table>{!rows.length?<div className="finder-empty"><strong>{empty}</strong></div>:null}</div>}
