"use client";

import { useRouter } from "next/navigation";
import { useState } from "react";
import { LoaderCircle, Plus, X } from "lucide-react";

type Field={name:string;label:string;type?:"text"|"number"|"date"|"textarea"|"select"|"checkbox";required?:boolean;options?:readonly string[];placeholder?:string};
const configs:Record<string,{module:string;title:string;fields:Field[]}>= {
  blockers:{module:"blockers",title:"Project blocker",fields:[{name:"title",label:"Blocker",required:true},{name:"category",label:"Category",type:"select",options:["land","utility","engineering","environmental","permitting","commercial","financing","legal","construction","operations","other"],required:true},{name:"severity",label:"Severity",type:"select",options:["low","medium","high","critical"],required:true},{name:"description",label:"Description",type:"textarea"},{name:"target_resolution_date",label:"Target resolution",type:"date"},{name:"status",label:"Status",type:"select",options:["open","monitoring","resolved","accepted","cancelled"],required:true}]},
  decisions:{module:"decisions",title:"Project decision",fields:[{name:"decision_title",label:"Decision",required:true},{name:"decision_date",label:"Decision date",type:"date",required:true},{name:"selected_option",label:"Selected option",required:true},{name:"rationale",label:"Rationale",type:"textarea",required:true},{name:"financial_impact",label:"Financial impact",type:"textarea"},{name:"schedule_impact",label:"Schedule impact",type:"textarea"},{name:"risk_impact",label:"Risk impact",type:"textarea"}]},
  interconnection:{module:"interconnection",title:"Interconnection request",fields:[{name:"service_territory",label:"Service territory",required:true},{name:"request_type",label:"Request type",required:true},{name:"requested_capacity_mw",label:"Requested MW",type:"number"},{name:"status",label:"Status",type:"select",options:["not_started","screening","preparing_application","submitted","feasibility_study","system_impact_study","facilities_study","agreement_negotiation","approved","withdrawn","rejected","suspended","unknown"],required:true},{name:"evidence_level",label:"Evidence level",type:"select",options:["nearby_infrastructure","preliminary_utility_feedback","formal_study_result","executed_interconnection_agreement"],required:true},{name:"next_action",label:"Next action",type:"textarea"},{name:"next_action_date",label:"Next action date",type:"date"}]},
  engineering:{module:"engineering",title:"Engineering deliverable",fields:[{name:"title",label:"Deliverable",required:true},{name:"deliverable_type",label:"Type",type:"select",options:["site_layout","production_model","single_line_diagram","equipment_schedule","civil_plan","grading_plan","drainage_plan","geotechnical_report","structural_design","interconnection_package","construction_drawings","as_built_drawings","other"],required:true},{name:"status",label:"Status",type:"select",options:["not_started","in_progress","delivered","approved","superseded"]},{name:"target_date",label:"Target date",type:"date"}]},
  epc:{module:"epc",title:"EPC proposal version",fields:[{name:"vendor_id",label:"EPC vendor record ID",required:true},{name:"version_number",label:"Version",type:"number",required:true},{name:"total_epc_cost",label:"Total EPC cost",type:"number"},{name:"cost_per_watt_dc",label:"Cost / W DC",type:"number"},{name:"cost_per_watt_ac",label:"Cost / W AC",type:"number"},{name:"status",label:"Status",type:"select",options:["received","clarification","shortlisted","recommended","selected","declined","expired"]},{name:"schedule_summary",label:"Schedule",type:"textarea"},{name:"proposal_expiration",label:"Proposal expiration",type:"date"}]},
  offtakers:{module:"offtakers",title:"Off-taker opportunity",fields:[{name:"facility",label:"Facility",required:true},{name:"location",label:"Location"},{name:"industry",label:"Industry"},{name:"estimated_annual_usage_kwh",label:"Annual usage kWh",type:"number"},{name:"credit_review_status",label:"Credit review status"},{name:"interest_level",label:"Interest level"},{name:"status",label:"Pipeline stage",type:"select",options:["identified","researched","contacted","discovery","data_requested","data_received","qualified","pricing_review","loi","term_sheet","ppa_negotiation","committed","declined","paused"],required:true},{name:"next_action",label:"Next action",type:"textarea"}]},
  ppa:{module:"ppa",title:"PPA scenario version",fields:[{name:"version_number",label:"Version",type:"number",required:true},{name:"term_years",label:"Term years",type:"number"},{name:"starting_price_per_kwh",label:"Starting $ / kWh",type:"number"},{name:"annual_escalator_pct",label:"Annual escalator %",type:"number"},{name:"contracted_energy_kwh",label:"Contracted energy kWh",type:"number"},{name:"status",label:"Status",type:"select",options:["concept","indicative","term_sheet_draft","term_sheet_issued","term_sheet_accepted","legal_drafting","negotiation","execution_ready"],required:true},{name:"legal_review_status",label:"Legal review status"}]},
  permitting:{module:"permits",title:"Permit requirement",fields:[{name:"requirement_type",label:"Requirement",required:true},{name:"responsible_agency",label:"Agency"},{name:"status",label:"Status",type:"select",options:["not_started","researching","required","preparing","submitted","under_review","approved","rejected","expired","not_required"],required:true},{name:"due_date",label:"Due date",type:"date"},{name:"expiration_date",label:"Expiration",type:"date"},{name:"cost",label:"Cost",type:"number"},{name:"notes",label:"Conditions / notes",type:"textarea"}]},
  incentives:{module:"incentives",title:"Project incentive",fields:[{name:"incentive_program_id",label:"Program record ID",required:true},{name:"eligibility_status",label:"Eligibility status",required:true},{name:"application_status",label:"Application status",required:true},{name:"estimated_value",label:"Estimated value",type:"number"},{name:"confirmed_value",label:"Confirmed value",type:"number"},{name:"deadline",label:"Deadline",type:"date"},{name:"next_action",label:"Next action",type:"textarea"}]},
  budget:{module:"budget",title:"Project budget version",fields:[{name:"version_number",label:"Version",type:"number",required:true},{name:"name",label:"Budget name",required:true},{name:"status",label:"Status",type:"select",options:["draft","review","approved","superseded"]},{name:"total_project_cost",label:"Total project cost",type:"number",required:true}]},
  capital_stack:{module:"capital_stack",title:"Capital stack version",fields:[{name:"version_number",label:"Version",type:"number",required:true},{name:"name",label:"Stack name",required:true},{name:"status",label:"Status",type:"select",options:["draft","review","approved","superseded"]},{name:"approved_project_cost",label:"Approved project cost",type:"number",required:true}]},
  capital:{module:"capital",title:"Capital stack item",fields:[{name:"capital_stack_version_id",label:"Capital stack version ID",required:true},{name:"capital_type",label:"Capital type",type:"select",options:["sponsor_equity","investor_equity","construction_debt","permanent_debt","tax_credit_transfer_proceeds","tax_equity","grant","rebate","loan_guarantee","seller_financing","equipment_financing","bridge_financing","other"],required:true},{name:"source",label:"Source"},{name:"amount",label:"Amount",type:"number",required:true},{name:"status",label:"Status",type:"select",options:["concept","researching","contacted","application","diligence","term_sheet","committed","closed","declined","withdrawn"]},{name:"expected_close_date",label:"Expected close",type:"date"},{name:"conditions",label:"Conditions",type:"textarea"}]},
  milestones:{module:"milestones",title:"Project milestone",fields:[{name:"section",label:"Workstream",required:true},{name:"task_name",label:"Milestone",required:true},{name:"task_description",label:"Description",type:"textarea"},{name:"status",label:"Status",type:"select",options:["not_started","in_progress","complete","blocked","waived","cancelled"]},{name:"target_date",label:"Target date",type:"date"},{name:"critical_path",label:"Critical path",type:"checkbox"}]},
  tasks:{module:"tasks",title:"Project task",fields:[{name:"title",label:"Task",required:true},{name:"description",label:"Description",type:"textarea"},{name:"category",label:"Category"},{name:"priority",label:"Priority",type:"select",options:["low","normal","high","critical"]},{name:"status",label:"Status",type:"select",options:["open","in-progress","waiting","completed","canceled"]},{name:"due_date",label:"Due date",type:"date"}]},
  construction:{module:"construction",title:"Construction progress update",fields:[{name:"title",label:"Update",required:true},{name:"status",label:"Status",required:true},{name:"record_type",label:"Workstream"},{name:"effective_date",label:"Report date",type:"date"},{name:"due_date",label:"Next due date",type:"date"},{name:"amount",label:"Cost impact",type:"number"},{name:"details",label:"Details",type:"textarea"}]},
  operations:{module:"operations",title:"Operating asset record",fields:[{name:"title",label:"Asset or operating record",required:true},{name:"status",label:"Status",required:true},{name:"record_type",label:"Type"},{name:"effective_date",label:"Effective date",type:"date"},{name:"due_date",label:"Next service date",type:"date"},{name:"details",label:"Details",type:"textarea"}]},
};

export function ProjectRecordForm({projectId,section}:{projectId:string;section:string}){const config=configs[section];const router=useRouter();const[open,setOpen]=useState(false);const[busy,setBusy]=useState(false);const[message,setMessage]=useState("");if(!config)return null;async function submit(formData:FormData){setBusy(true);setMessage("");const values:Record<string,FormDataEntryValue|number|boolean>=Object.fromEntries(formData.entries());for(const field of config.fields){if(field.type==="number"&&values[field.name]!=="")values[field.name]=Number(values[field.name]);if(field.type==="checkbox")values[field.name]=formData.get(field.name)==="on";}const response=await fetch(`/api/projects/${projectId}/records/${config.module}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(values)});const body=await response.json();setBusy(false);if(!response.ok)return setMessage(body.error||"Record could not be saved.");setOpen(false);router.refresh()}return <><button className="finder-button finder-button--primary" onClick={()=>setOpen(true)}><Plus size={15}/>Add record</button>{open?<div className="project-dialog-backdrop" role="presentation" onMouseDown={()=>!busy&&setOpen(false)}><section className="project-dialog" role="dialog" aria-modal="true" aria-labelledby="record-dialog-title" onMouseDown={event=>event.stopPropagation()}><button className="project-dialog-close" onClick={()=>setOpen(false)} aria-label="Close"><X/></button><p className="finder-eyebrow">Project operations</p><h2 id="record-dialog-title">{config.title}</h2><form action={submit} className="project-dialog-form project-record-form">{config.fields.map(field=><label key={field.name} className={field.type==="checkbox"?"project-checkbox":""}>{field.type==="checkbox"?<><input name={field.name} type="checkbox"/> {field.label}</>:<>{field.label}{field.type==="textarea"?<textarea className="finder-textarea" name={field.name} required={field.required} placeholder={field.placeholder}/>:field.type==="select"?<select className="finder-select" name={field.name} required={field.required}>{field.options?.map(option=><option value={option} key={option}>{option.replaceAll("_"," ")}</option>)}</select>:<input className="finder-field" name={field.name} type={field.type||"text"} step={field.type==="number"?"any":undefined} required={field.required} placeholder={field.placeholder}/>}</>}</label>)}<button disabled={busy} className="finder-button finder-button--primary">{busy?<LoaderCircle className="spin"/>:<Plus/>}Save record</button>{message?<p role="alert" className="project-action-error">{message}</p>:null}</form></section></div>:null}</>}
